- content/spin/go-components.md
> Updating TinyGo support

- content/spin/go-components.md
https://github.com/fermyon/developer/pull/174#discussion_r1004465620
> Update TinyGo version copy

- content/cloud/deploy.md
- content/cloud/develop.md
- content/cloud/quickstart.md
- content/spin/install.md
- content/spin/quickstart.md
To help prevent this in the future https://github.com/fermyon/spin/issues/858
Adding '-L' so if anyone copies the command to automation, redirects in the future will resolve.
> Adding --location to curl commands for install script

- .build/check-broken-links.sh
- .github/workflows/build.yml
- content/cloud/fermyon-cloud.md
- content/cloud/quickstart.md
- content/spin/deploying-to-fermyon.md
- content/spin/index.md
- package-lock.json
- package.json
- templates/content_bottom.hbs
Signed-off-by: Rajat Jindal <rajatjindal83@gmail.com>
> check broken links

- content/cloud/develop.md
> Add annotations to cloud/develop.md

- content/cloud/deploy.md
Fixed a few typos, resolves [CON-2](https://linear.app/fermyon/team/CON/all)
Signed-off-by: MacKenzie Olson <mackenzie.olson@fermyon.com>
> Grammatical fixes on deploy.md

- content/cloud/fermyon-cloud.md
Adding hyperlink, closes [CON-3](https://linear.app/fermyon/issue/CON-3/add-missing-hyperlink-in-cloud-explained-article)
Signed-off-by: MacKenzie Olson <mackenzie.olson@fermyon.com>
> Update fermyon-cloud.md 

- templates/404.hbs
- templates/main.hbs
> WIP: Add links to homepage and spin/cloud docs on 404

- content/spin/install.md
Relates to https://github.com/fermyon/developer/pull/237
> update install doc with support for Linux ARM64

- .build/check-broken-links.sh
> filter link checker output and retry for transient errors

- content/cloud/faq.md
> Add upload package limit

- content/cloud/cli-reference.md
This is in relation to issue https://github.com/fermyon/developer/issues/262
> Update CLI reference

- templates/bartholomew_sidebar.hbs
> fix titlecase lint

- .github/workflows/deploy.yml
Only deploy website if org is fermyon (disable for forks)
> chore(deploy.yml): only attempt website deploy if org is fermyon

- .build/check-broken-links.sh
- content/spin/install.md
> make link checking verbose by printing to stderr and fix broken link

- content/spin/install.md
> Update Spin installation instructions (via Cargo) to current version

- content/bartholomew/contributing-bartholomew.md
- content/bartholomew/index.md
- content/bartholomew/quickstart.md
Signed-off-by: Vaughn Dice <vaughn.dice@fermyon.com>
> chore(*): update spin domain/urls

- content/spin/javascript-components.md
> Update to show and resolve potential Windows error

- templates/spin_sidebar.hbs
> fix missing sidebar entry

- content/common/cli-reference.md
- content/common/contributing-docs.md
- templates/cloud_sidebar.hbs
- templates/common_main.hbs
- templates/common_sidebar.hbs
- templates/spin_sidebar.hbs
Signed-off-by: tpmccallum <tim.mccallum@fermyon.com>
Adding new common folder and templates to house resources/pages which are intended to be used across two or more project templates.
> Adding new common area for shared resources

- content/spin/plugin-authoring.md
> add codeblock annotations and prefix $

- content/cloud/quickstart.md
Resolves https://github.com/fermyon/developer/issues/260
> Update docs to show spin in system path

- spin.toml
> Add redirects which remove redundant resources

- spin.toml
> Resolve 404 errors (as reported by Google Search Console; legacy links that do not resolve)

- spin.toml
> Update one outlier from GSC

- content/spin/install.md
Referes to issue https://github.com/fermyon/developer/issues/292
> Update to remove the passing of specific version number (unless it is appropriate i.e. trying to install a specific version on purpose)

- content/common/contributing-docs.md
> Update ToC for proper rendering

- templates/spin_sidebar.hbs
> Move OCI menu from Advanced to Tutorial

- content/spin/spin-oci.md
> fix code block annotations

- content/common/contributing-docs.md
> Add bart cli instructions

- content/spin/install.md
> Adjust position of command which recommends adding Spin to system path

- content/events/2023-02-community-qanda.md
> Update Community Meeting to 09th March 6pm UTC

- content/spin/deploying-to-fermyon.md
> Add headings to enable ToC rendering

- templates/home.hbs
> Homepage: consider not opening new tabs

- package-lock.json
- static/css/styles.css
- static/sass/styles.scss
> Updated `scss` instead of `css` so that rendering is sustainable.

- content/spin/spin-oci.md
> Update first heading to H2 (instead of H1)

- content/spin/spin-oci.md
> Update 0.8.0 code

- templates/content_top.hbs
> add heap for user journey insights

- content/common/cli-reference.md
> Remove extra ending to code block

- static/css/styles.css
- static/sass/styles.scss
> increase h2 line-height

- content/spin/kv-store.md
Just adding embedded video and updating ToC.
> Add embedded video, add rich results, update ToC

- content/spin/kv-store.md
> Update Markdown for requests

- static/css/styles.css
- static/sass/styles.scss
> allow scroll on long ToCs

- content/spin/python-components.md
> Update publish time so this is live immediately

- README.md
> Update readme with contribution suggestion

- content/common/cli-reference.md
> Fix spin new vs add explanation

- content/common/cli-reference.md
> Update CLI Reference in accordance with v0.10.0 release

- static/css/styles.css
- static/sass/styles.scss
> fix inline codeblock styling inside table

- content/common/contributing-docs.md
> Add video version of contributing to the docs

- content/googleea373cbb8f1dde18.html
> Add google verification file - console is reporting no registration present

- content/googleea373cbb8f1dde18.html
- content/googleea373cbb8f1dde18.md
- templates/google_verification.hbs
> Verify developer docs subdomain

- content/cloud/faq.md
Sorry, folks, I let a sneaky _actually_ broken link slip through in the manifest reference PR.  This fixes it!
> Fixed broken link in FAQ

- spin.toml
Follow-up from https://github.com/fermyon/developer/pull/434#pullrequestreview-1331800637
> feat(spin.toml): add redirect for /spin/configuration

- content/spin/writing-apps.md
+ make clear what attribute is for hello_world example
> ref(writing-apps): update spin_manifest_version

- content/spin/install.md
> Move build toolchain information to where it is needed

- content/spin/javascript-components.md
> add more working npm packages

- content/spin/manifest-reference.md
> Fixes "Edit on GitHub" button for manifest reference

- static/js/main.js
- static/js/src/modules/multiTab.js
> js: remove scroll jank on changing tabs

- static/css/styles.css
- static/sass/styles.scss
> fix code block scrollbar

- static/js/main.js
- static/js/src/modules/multiTab.js
This PR allows specifying what tabs to be selected on page load using query parameters. The query parameters for the tab names are prefixed with `multitab`. An example URL would be
```
http://localhost:3000/spin/quickstart?multitab_os=Linux&multitab_sdk-type=TinyGo
```
> allow toggling multitabs from query params

- content/spin/install.md
Small clarification about WSL and using Windows natively.
> Updating Windows install instructions

- content/spin/javascript-components.md
> add a quick reference to the router in javascript

- content/common/contributing-docs.md
> Add `$` to make `npm` commands work with selective copy

- content/spin/quickstart.md
> Update embedded video

- content/spin/dynamic-configuration.md
Pending https://github.com/fermyon/spin/pull/1234
> Update config env prefix to SPIN_CONFIG

- static/css/styles.css
- static/sass/styles.scss
> css fixes for h4 and toc

- static/css/styles.css
- static/sass/styles.scss
Follow up to #500, tweaking the spacing and color of the TOC column.
> slight adjustments to the toc css

- content/cloud/user-settings.md
> Remove abbreviation from menu text

- .github/workflows/deploy-preview.yml
do not run preview workflow on forks
> do not run preview workflow on forks

- .build/check-broken-links.sh
- add initial website health check to fail fast if root url isn't returning 200
- also fix behavior where blc would exit non-zero but overall check passes
> feat(check-broken-links.sh): add initial website health check

- content/spin/javascript-components.md
> Add suggestion to decode request body to text or JSON

- content/spin/managing-plugins.md
> Update the example to the latest version - in case someone uses cut/paste

- content/events/2023-devopsdays-copenhagen.md
- content/events/2023-gluecon.md
- content/events/2023-ossummit-us.md
> Update event slider

- content/cloud/changelog/custom-fermyon-subdomain.md
> Custom subdomain changelog

- content/cloud/custom-fermyon-subdomain.md
- Replace `:` with `.` 
- Add space between text and image
- Take image syntax out of code block and put on its own new line
> Update docs (minor editing fixes)

- content/bartholomew/markdown.md
closes https://github.com/fermyon/feedback/issues/21
> remove non needed enable shortcodes to fix formatting

- .github/pull_request_template.md
> Add reminder to associate existing blog with docs

- content/spin/http-trigger.md
associated PR: https://github.com/fermyon/spin/pull/1298
> add docs for spin-client-addr

- content/common/cli-reference.md
- content/common/contributing-docs.md
- content/spin/install.md
> Update Spin from 1.1 to 1.2

- content/spin/install.md
> Update install.md to ensure Spin is copied to correct path

- content/spin/index.md
- content/spin/see-what-people-have-built-with-spin.md
- templates/spin_sidebar.hbs
> Built with spin

- content/spin/install.md
Just added 2 new blank lines to resolve Build Tests
> Add line spacings to fix broken tests

- static/css/styles.css
- static/sass/styles.scss
- templates/home.hbs
> make the entire project card clickable

- content/spin/install.md
> Bump 1.2.0 to 1.2.1

- static/css/styles.css
- static/sass/styles.scss
Before 
After
Bonus content (light mode)
PS: @flynnduism is a CSS wizard!
> Add border to images to distinguish between background and images

- templates/home.hbs
> fix type to open links in the same tab on homepage

- content/cloud/quickstart.md
> remove hardcoded border

- content/spin/upgrade.md
- templates/spin_sidebar.hbs
> Upgrade Spin: Adding first draft to prompt discussion

- content/spin/upgrade.md
> Add Spin release image to page

- static/css/styles.css
- static/sass/styles.scss
fixes layout shift on page load when initializing the multitab blocks.
> fix jank on multitab on codeblock load

- content/cloud/variables.md
Fixes template error by properly escaping shortcodes.
> escape shortcodes where not required

- content/cloud/changelog/cloud-config.md
> variables changelog

- content/spin/variables.md
> Fix improper ts config api example

- content/cloud/pricing-and-billing.md
- spin.toml
> Moving forward publishing time for pricing.md

- content/cloud/variables.md
- content/spin/python-components.md
> Fixed error in Spin Python - Redis Outbound code sample

- content/spin/contributing-docs.md
> Update contributing-docs.md - how to point to shortcodes via bart command

- .github/workflows/build.yml
Related content:
https://github.com/fermyon/developer/issues/715
https://github.com/fermyon/developer/pull/719
> Update build.yml to use --shortcodes shortcodes

- content/cloud/faq.md
Sorry.  My spell checker was insistently sitting on "1 problem" and it was like having sand in my shoe.
> Fix typo in cloud FAQ

- content/spin/build.md
- content/spin/running-apps.md
- content/spin/troubleshooting-application-dev.md
- templates/spin_sidebar.hbs
LOOK HOW MANY MEDICAL PUNS I AVOIDED DO YOU KNOW HOW HARD THAT WAS
> `spin doctor` docs

- content/spin/javascript-components.md
- content/spin/kv-store-api-guide.md
- content/spin/kv-store-tutorial.md
- content/spin/redis-outbound.md
- content/spin/sqlite-api-guide.md
- content/spin/variables.md
> update docs to reflect the changes in the js sdk

- content/spin/install.md
> Replace outdated Spin version reference

- content/spin/kubernetes.md
> chore: bump version of the containerd-wasm-shims k3d image to 0.8.0

- content/api/hub/contributing.md
> Adding information about npm install

- content/spin/contributing-spin.md
> Added cargo build via --bin flag

- content/api/hub/template_http_go.md
> Go HTTP template

- content/api/hub/template_redis_go.md
- content/api/hub/template_redis_rust.md
> Redis templates

- content/api/hub/dioxus.md
- content/api/hub/like-button.md
> Dioxus and Like Button samples

- content/api/hub/sample_todo.md
- content/api/hub/template_kv_explorer.md
- content/api/hub/template_nextjs.md
- content/api/hub/template_spin_fileserver.md
> added static file server, todo, and other content

- content/api/hub/sample_openaichat_ts.md
- content/api/hub/template_openaichat_ts.md
> Added OpenAI Chat template

- content/cloud/changelog/cloud-custom-domains.md
Cloud Custom Domains Changelog
**Embargo**
> Changelog: Create cloud-custom-domains.md

- content/cloud/fermyon-cloud.md
> removed ref to old name

- content/cloud/noops-sql-db.md
> Add cloud plugin version

- content/cloud/custom-domains-tutorial.md
> Add inline video Re: custom-domains-tutorial

- content/spin/running-apps.md
> Update text and add cross link between documentation and related blog post.

- content/spin/see-what-people-have-built-with-spin.md
> Just a cross link from developer documentation to recent blog post

- content/api/hub/sample_redirect.md
A new Spin Up Hub submission to showcase a redirect app built using Spin.
> Spin Up Hub: Redirect app

- content/spin/go-components.md
- content/spin/javascript-components.md
- content/spin/python-components.md
- content/spin/rdbms-storage.md
- content/spin/rust-components.md
> Update TS-JS, TinyGo and Python Re: KV & RDBMS

- content/spin/sqlite-api-guide.md
closes https://github.com/fermyon/developer/issues/788
> Add exception handling sentence.

- content/spin/kubernetes.md
> Update the Kubernetes docs with the helm installer

- content/spin/kv-store-tutorial.md
> Update kv example's repository URL

- content/spin/spin-oci.md
- templates/spin_sidebar.hbs
Closes https://github.com/fermyon/developer/issues/436
> Remove OCI acronym and adjust wording

- content/api/hub/sample_kv_in_typescript.md
> Add example of KV storage

- content/spin/install.md
> Add brew installation option to documentation.

- content/api/hub/sample_kv_in_typescript.md
#820 is probably the real fix.
> Shortening title for better layout

- content/spin/cache.md
> Update cache.md to include Homebrew plugin and template locations

- content/spin/install.md
> Adding selective copy where it would be convenient.

- content/api/hub/plugin_spin_pluginify.md
> Update pluginify hub entry with registry install

- content/cloud/noops-sql-db.md
See here: https://discord.com/channels/926888690310053918/1133472877224665178
> Update NoOps sql article to address user feedback on `spin up --sqlite` not being easy to find.

- content/spin/install.md
> Update codeblocks to use md

- content/spin/upgrade.md
> Add brew update and upgrade to Spin upgrade page

- package.json
- static/css/styles.css
- static/sass/developer-include-feedback.scss
- static/sass/styles.scss
> fix styling for feedback

- content/api/hub/sample_feed_dog.md
> Add sample Feed the Dog app

- content/api/hub/sample_hugo.md
> Make description display full in the Hub's card; no spillover/overlap.

- content/api/hub/sample_newsreader_ai.md
- content/api/hub/sample_silly_walk_ai.md
> Add two new examples for AI

- content/api/hub/sample_sentiment_analysis.md
> Add sentiment analysis as spin up hub sample

- content/cloud/serverless-ai.md
- content/spin/serverless-ai-tutorial.md
> Be clear about adding spin to path

- content/spin/go-components.md
> Update TinyGo and Go versions in documentation

- content/spin/language-support-overview.md
Small update to include Serverless AI as Not Supported for the C# SDK
> Update SDK support table

- content/api/hub/template_qwik_frontend.md
> qwik: fix link and typo

- spin-up-hub/src/store.js
Adds 404 Handling to hub previews. 
fixes #855
> add 404 handling for hub previews

- .build/check-broken-links.sh
> Update link checker

- content/spin/build.md
> Update build command output to not include RUST_LOG

- content/cloud/faq.md
> Added maximum KV value size to faq.md

- content/cloud/faq.md
> Add redeploy error to FAQ

- content/spin/serverless-ai-tutorial.md
> [Ready for approve/merge] Update model download URLs to a specific commit (pin them)

- content/spin/serverless-ai-tutorial.md
Radu linked to a model.safetensors commit which I am now adding as part of a new PR. Apologies for not adding it to the original PR Re: this same topic.
> Add specific commit for model.safetensors

- content/spin/kv-store-api-guide.md
I could not get the code to compile, unless I handled the `null` case (key not found).
> Fix TS KV store API cod

- content/cloud/cloud-command-reference.md
Relates to https://github.com/fermyon/cloud-plugin/pull/94
> Add new info command and update Re: 0.3.0 release

- content/spin/ai-sentiment-analysis-api-tutorial.md
- content/spin/key-value-store-tutorial.md
- content/spin/registry-tutorial.md
- content/spin/url-shortener-tutorial.md
- spin.toml
- templates/spin_sidebar.hbs
✅ content/spin/ai-sentiment-analysis-api-tutorial.md  
✅ content/spin/key-value-store-tutorial.md   
✅ content/spin/registry-tutorial.md
✅ content/spin/url-shortener-tutorial.md
> Be consistent with page names, titles and menu

- content/cloud/serverless-ai.md
> Update spin requirements for AI

- content/cloud/linking-applications-to-resources-using-labels.md
> Change date to present

- content/cloud/cloud-command-reference.md
- content/spin/cli-reference.md
A few fixes to CLI references for Cloud Plugin 0.4.0 and Spin 1.5
> Fix CLI references

- content/spin/cli-reference.md
> Add content to Spin Doctor 1.5 (missing)

- content/cloud/changelog/spin-cloud-v0-4-0.md
> Fix broken links

- content/api/hub/sample_crossword_helper.md
- []  Does this PR have a new menu item (anywhere in `templates/*.hbs` files) that points to a document `.md` that is set to publish in the future? If so please only publish the `.md` and `.hbs` changes in real-time (otherwise there will be a menu item pointing to a `.md` file that does not exist)
> Add crossword-helper sample

- content/api/hub/template_sqlite_explorer.md
> adding SUH card for sqlite-explorer

- content/api/hub/plugin_spin_cloud_gpu.md
> spin-cloud-gpu SUH card

- content/cloud/faq.md
> Update faq.md to reflect NoOps DB quota

- content/spin/serverless-ai-hello-world.md
TO DO: Create sample code in the `ai-examples` folder. 
✅ content/spin/serverless-ai-hello-world.md
> Added serverless AI tutorial for beginners

- content/cloud/data-redis.md
> Redis link update

- content/spin/v2/install.md
- content/spin/v2/managing-plugins.md
- content/spin/v2/plugin-authoring.md
- content/spin/v2/upgrade.md
- content/spin/v2/writing-apps.md
KEEP COUNTING THOSE SQUARE BRACKETS!!!
tpmccallum@192-168-1-22 developer % bart check content/spin/v2/install.md
✅ content/spin/v2/install.md
tpmccallum@192-168-1-22 developer % bart check content/spin/v2/managing-plugins.md 
✅ content/spin/v2/managing-plugins.md
tpmccallum@192-168-1-22 developer % bart check content/spin/v2/plugin-authoring.md 
✅ content/spin/v2/plugin-authoring.md
tpmccallum@192-168-1-22 developer % bart check content/spin/v2/upgrade.md         
✅ content/spin/v2/upgrade.md
tpmccallum@192-168-1-22 developer % bart check content/spin/v2/writing-apps.md 
✅ content/spin/v2/writing-apps.md
> Working my way through the sections, part 1

- content/spin/v2/quickstart.md
Note the rewrite of the manifest explainer paragraph, since we've teased apart the `trigger` and `component` and so need to explain each.  Please check that the new para is okay, and that the copypasta changes the right things in the right places.
**Please double check that I have the right number of square brackets on each section.** `[[trigger.http]]` should always have two; `[component.whatever...]` should always have one.
tpmccallum@192-168-1-22 developer % bart check content/spin/v2/quickstart.md 
✅ content/spin/v2/quickstart.md
> Update quick start to v2 (except video)

- content/spin/v2/cli-reference.md
✅ content/spin/v2/cli-reference.md
> Version 2.0 CLI Reference - first draft

- content/spin/v2/http-outbound.md
- content/spin/v2/http-trigger.md
> Add notes about streaming HTTP being experimental

- content/spin/v2/go-components.md
- content/spin/v2/javascript-components.md
- content/spin/v2/other-languages.md
- content/spin/v2/python-components.md
- content/spin/v2/rust-components.md
✅ content/spin/v2/go-components.md
✅ content/spin/v2/javascript-components.md
✅ content/spin/v2/other-languages.md
✅ content/spin/v2/python-components.md
✅ content/spin/v2/rust-components.md
> Spin 2 language guides

- content/spin/v2/language-support-overview.md
✅ content/spin/v2/language-support-overview.md
> Update Go support matrix for MySQL and Postgres

- content/spin/v2/serverless-ai-api-guide.md
> Fix broken link

- templates/spin_sidebar_v2.hbs
> Add v1 manifest reference to v2 sidebar menu

- templates/spin_sidebar_v2.hbs
> Add missing hello world example to menu

- content/spin/v2/javascript-components.md
✅ content/spin/v2/javascript-components.md
---
---
> Updating Javascript article to Spin 2.0

- content/spin/v1/serverless-ai-hello-world.md
- content/spin/v2/ai-sentiment-analysis-api-tutorial.md
- content/spin/v2/key-value-store-tutorial.md
- content/spin/v2/serverless-ai-hello-world.md
- content/spin/v2/template-authoring.md
- package-lock.json
- spin-up-hub/package-lock.json
**Bart check**
tpmccallum@192-168-1-22 developer % bart check content/spin/v2/ai-sentiment-analysis-api-tutorial.md 
✅ content/spin/v2/ai-sentiment-analysis-api-tutorial.md
tpmccallum@192-168-1-22 developer % bart check content/spin/v2/key-value-store-tutorial.md
✅ content/spin/v2/key-value-store-tutorial.md
tpmccallum@192-168-1-22 developer % bart check content/spin/v2/serverless-ai-hello-world.md 
✅ content/spin/v2/serverless-ai-hello-world.md
tpmccallum@192-168-1-22 developer % bart check content/spin/v2/template-authoring.md
✅ content/spin/v2/template-authoring.md
**npm run test**
Closing #957
Closing #958
This is the PR meant to adress the above two issues. Current a rough first draft, but will keep updating as I get more done.
> Updating Spin tutorials for 2.0 release

- content/spin/v2/language-support-overview.md
> Link from language supp. overview to AI page (remove extra hop)

- content/cloud/develop.md
- content/spin/v1/ai-sentiment-analysis-api-tutorial.md
- content/spin/v1/javascript-components.md
- content/spin/v1/key-value-store-tutorial.md
- content/spin/v1/python-components.md
- content/spin/v1/quickstart.md
- content/spin/v1/serverless-ai-hello-world.md
- content/spin/v1/spin-application-structure.md
- content/spin/v2/ai-sentiment-analysis-api-tutorial.md
- content/spin/v2/javascript-components.md
- content/spin/v2/key-value-store-tutorial.md
- content/spin/v2/python-components.md
- content/spin/v2/quickstart.md
- content/spin/v2/serverless-ai-hello-world.md
> Update example code to use consistent email and name

- content/spin/v2/quickstart.md
Added youtube video to the quickstar guide.
> Added Video to the Quickstart guide

- .github/workflows/deploy.yml
- deploy/fermyon-developer.nomad
Closes https://github.com/fermyon/developer/issues/1015
> bump spin v2

- downloads/install.sh
Updated the tense of step 3 and 4 so that the steps are consistent. 
> Updates text to use the same tense across all steps

- content/api/hub/template_zola_ssg.md
> added zola ssg to SUH

- content/api/hub/template_zola_ssg.md
> fixed typo in zola-ssg SUH card

- content/spin/v2/language-support-overview.md
> Spin 2 does not yet support C#

- content/cloud/changelog/serverless-ai-open-beta.md
> Add twitter card to serverless ai changelog post

- content/spin/v2/rust-components.md
> Fix outbound redis Rust example that was still using SDK v1

- content/cloud/changelog/spin-cloud-v0-5-1.md
- content/spin/v1/managing-plugins.md
- content/spin/v2/managing-plugins.md
> adding spin cloud plugin patch update changelog

- content/cloud/changelog/spin-cloud-v0-5-1.md
> fixed title for v0.5.1 patch update

- content/spin/v1/kubernetes.md
- content/spin/v2/kubernetes.md
> Adding a feedback form in k8s doc

- content/spin/v2/key-value-store-tutorial.md
> Add missing `spin up` command.

- spin-up-hub/src/components/ContentFilter.vue
- spin-up-hub/src/components/HubIntro.vue
- spin-up-hub/src/components/PreviewModal.vue
- templates/content_footer.hbs
- templates/content_navbar.hbs
- templates/home.hbs
Adds [Goal event triggers](https://plausible.io/docs/goal-conversions) so we can get Plausible info for certain clicks and actions.
> add plausible goal events

- content/cloud/data-redis.md
> Update port number and protocol - example was not working as is

- content/spin/v2/contributing-docs.md
> Document scheduling menu items for timed release

- content/api/hub/sample_http_auth_middleware.md
> Fix link to GitHub repository.

- content/cloud/develop.md
- content/cloud/faq.md
- content/cloud/variables.md
- content/spin/v2/ai-sentiment-analysis-api-tutorial.md
- content/spin/v2/cli-reference.md
- content/spin/v2/javascript-components.md
- content/spin/v2/kv-store-api-guide.md
- content/spin/v2/quickstart.md
- content/spin/v2/redis-trigger.md
- content/spin/v2/running-apps.md
- content/spin/v2/rust-components.md
- content/spin/v2/serverless-ai-api-guide.md
- content/spin/v2/serverless-ai-hello-world.md
- content/spin/v2/spin-application-structure.md
- content/spin/v2/sqlite-api-guide.md
- content/spin/v2/url-shortener-tutorial.md
- content/spin/v2/variables.md
- content/spin/v2/writing-apps.md
> Spin v2.1.0 Documentation

- static/css/styles.css
- static/sass/developer-color-dark.scss
- static/sass/developer-include-topbar.scss
Fixes #884 
The blur overlay seemed odd and at times slow, so I decided to replace it with a dim animation. 
If that seems acceptable, we can merge the PR else I will look at the blur animation.
> replace blur with dim transition

- content/spin/v2/kubernetes.md
This is for work against #1109 but I currently have more questions than just "you don't need the Dockerfile" so it is WIP for now.
> Update k8s docs to integrated registry command

- spin-up-hub/src/router.js
- spin-up-hub/src/store.js
> handle browser back when preview view

- spin-up-hub/src/components/ContentListing.vue
- spin-up-hub/src/store.js
fixes: #1097 
Hey @itowlson, can you review this PR? I took up your suggestion from my last PR i.e., #1111. Please let me know if any further changes need to be made.
> Trying to fix the overall performance of the hub search

- static/css/styles.css
- static/js/main.js
- static/js/src/modules/search.js
- static/sass/developer-include-search.scss
- templates/content_navbar.hbs
Adds search to mobile view. 
Link to test: https://fermyon-developer-twia6xje.fermyon.app/
> add search icon for mobile

- content/spin/v1/cli-reference.md
- content/spin/v2/cli-reference.md
> fix links in cli reference

- content/spin/v2/see-what-people-have-built-with-spin.md
> Add dev.to article link to docs

- content/spin/v2/dynamic-configuration.md
> Fix broken link (vault variable test moved in Spin repo)

- content/spin/v2/dynamic-configuration.md
> Fix vault password/secret

- content/spin/v2/dynamic-configuration.md
> Update curl commands in vault example

- content/spin/v2/dynamic-configuration.md
This PR will only pass the tests once the https://github.com/fermyon/spin/pull/2241 is merged and the example app URL is live.
> Add new example app to docs

- .build/check-broken-links.sh
> Exclude links that are working

- static/css/styles.css
- static/js/main.js
- static/js/src/modules/utils.js
- static/sass/styles.scss
> Adding anchor-link to individual fields within the spin documentation

- content/spin/v1/http-outbound.md
- content/spin/v1/rdbms-storage.md
- content/spin/v1/redis-outbound.md
- content/spin/v1/rust-components.md
- content/spin/v2/http-outbound.md
- content/spin/v2/rdbms-storage.md
- content/spin/v2/redis-outbound.md
- content/spin/v2/rust-components.md
> Update Rust example links

- content/wasm-languages/javascript.md
Closes https://github.com/fermyon/developer/issues/1183
> Create JS example in Wasm languages section

- content/api/hub/sample_router.md
I spoke to @technosophos about switching the source of the example to the fermyon org and we are in agreement.
> update python router sample to componentize-py

- content/cloud/noops-sql-db.md
> add note about using sqlite3 for local development with sqlite

- content/spin/v2/http-outbound.md
> Subdomain wildcards

- content/spin/v2/http-outbound.md
**This is part of Spin 2.4.**  It should not be merged until Spin 2.4 is released.
> Service chaining

- static/js/main.js
- static/js/src/modules/utils.js
> Enhanced the anchor-link to individual table rows

- content/spin/v2/language-support-overview.md
Signed-off-by: tpmccallum <tim.mccallum@fermyon.com>
> Adding URL for Python Redis Trigger Support (same as Rust etc.)

- content/spin/v2/python-components.md
- content/spin/v2/spin-in-pods-legacy.md
- content/wasm-languages/python.md
> Update Python instructions (include venv)

- content/spin/v1/contributing-spin.md
- content/spin/v2/contributing-spin.md
- templates/spin_sidebar_v2.hbs
Aligning ToC title with doc title
> small toc update

- content/spin/v2/variables.md
> Replacing python code with typescript in spin docs

- content/spin/v2/variables.md
> Give example of how to build, run and test the application.

- .github/pull_request_template.md
> Check for carriage return

- content/cloud/linking-applications-to-resources-using-labels.md
- content/spin/v2/key-value-store-tutorial.md
> Sharing info with cloud apps

- content/spin/v2/http-outbound.md
> Private endpoints in Spin 2.5

- templates/content_bottom.hbs
- templates/content_top.hbs
Removing Clearbit and adding CommonRoom. This PR updates the JS code and the cookie consent settings.
> Add commonroom to developer site

- content/spin/v2/cli-reference.md
> Fix spin kube reference blocks

- content/api/hub/plugin_spin_cron_trigger.md
> Lower case fermyon to ensure checkmark displays in the Spin Up Hub

- content/cloud/noops-sql-db.md
> Requires -d option when passing in database

- static/js/main.js
- static/js/src/modules/multiTab.js
> reverse the version list and always highlight the latest version

- spin-up-hub/src/store.js
unescapes the summary on hub cards
> unescape html in description in hub cards

- content/api/hub/template_http_python.md
- content/cloud/develop.md
- content/cloud/github-actions.md
- content/cloud/variables.md
- content/spin/v2/ai-sentiment-analysis-api-tutorial.md
- content/spin/v2/build.md
- content/spin/v2/key-value-store-tutorial.md
- content/spin/v2/python-components.md
- content/spin/v2/quickstart.md
- content/spin/v2/serverless-ai-hello-world.md
- content/spin/v2/writing-apps.md
- content/wasm-languages/python.md
Fixes https://github.com/fermyon/developer/issues/1298
> Update documentation to clarify Python version required

- content/cloud/noops-sql-db.md
> Fix formatting in code sections

- content/spin/v1/rust-components.md
- content/spin/v2/http-outbound.md
- content/spin/v2/http-trigger.md
- content/spin/v2/kv-store-api-guide.md
- content/spin/v2/rdbms-storage.md
- content/spin/v2/redis-outbound.md
- content/spin/v2/redis-trigger.md
- content/spin/v2/rust-components.md
- content/spin/v2/serverless-ai-api-guide.md
- content/spin/v2/sqlite-api-guide.md
- content/spin/v2/variables.md
> Update Rust SDK links

- content/spin/v2/manifest-reference-v1.md
> Update GitHub page url in frontmatter

- content/spin/v2/serverless-ai-hello-world.md
> GitHub path correction

- content/spin/v2/triggers.md
> Just a quick note about the 7th field in cron

- .build/check-broken-links.sh
- content/spin/v2/observing-apps.md
> Improve OTel docs

- content/spin/v2/running-apps.md
> Adjust --from / -f option in documentation

- content/spin/v2/dynamic-configuration.md
> Update application variables documentation with a note on precedence

- content/wasm-languages/c-lang.md
Closes https://github.com/fermyon/developer/issues/1318
✅ content/wasm-languages/c-lang.md
> Update from version 14 to version 20

- content/spin/v2/dynamic-configuration.md
> Fixing 'type' field in SQLite storage runtime configuration

- content/spin/v2/dynamic-configuration.md
Follow-up to https://github.com/fermyon/developer/issues/1332
Closes https://github.com/fermyon/developer/issues/1332
> docs(dynamic-configuration.md): add spin type to sqlite runtime config

- content/spin/v2/dynamic-configuration.md
Last one, promise.
(Until the next one.)
> docs(dynamic-configuration.md): one more spot needing type

- content/api/hub/sample_code_pls.md
- package-lock.json
- package.json
- spin-up-hub/package-lock.json
Adding a new card of code bot to Spin Up Hub! 
> Add Code-pls SUH card

- content/spin/v2/serverless-ai-api-guide.md
Aiming to address user feedback asking which version of Spin to use in response to this error.
> Explain "local LLM operations not supported" error

- content/api/hub/plugin_spin_otel.md
- content/spin/v2/observing-apps.md
> adding otel plugin

- content/wasm-languages/grain.md
> fix code block formattng for grain

- .build/check-broken-links.sh
fix false positive link which is leading to CI to be red.
> ignore false positive link

- content/api/hub/sample_tera.md
> Updating Spin Hub with Tera Sample

- templates/spin_main.hbs
@itowlson here are the crimes needed to make the spin sidebar work with v3.
> fix if else clause in spin_main.hbs

- content/spin/v3/migration-v2-v3.md
- templates/spin_sidebar_v3.hbs
For discussion of how we want to present this
Breaking changes checklist at https://github.com/fermyon/spin/issues/2815
> Breaking changes info

- content/spin/v3/running-apps.md
> Application splitting

- content/spin/v3/rdbms-storage.md
> Clarify MySQL/Postgres in RDBMS examples

- content/cloud/faq.md
- content/spin/v3/writing-apps.md
> Updated Cloud feature support

- content/spin/v3/extending-and-embedding.md
Partial fix for #1411.  I wimped out on talking about customising factors.  My brain is gonna need to work up to that one.
> Update custom trigger sample to v3

- content/cloud/data-redis.md
The Code sample was using APIs provided by an old Spin SDK
> [cloud]: Fix data on Redis example code

- content/spin/v3/ai-sentiment-analysis-api-tutorial.md
Companion: https://github.com/fermyon/ai-examples/pull/51
> Update sentiment-analysis-tutorial for Python

- downloads/install.sh
Reverts fermyon/developer#1438
> Revert "Work around Cloud plugin install woe"

- static/js/src/modules/search.js
> Fix search to only show releavnt v2 or v3 Spin docs

- static/js/main.js
Follow up on https://github.com/fermyon/developer/pull/1454
This PR adds the bundled script.
> Check in the bundled-script to fix search

- content/events/2025-cloud-rejekts.md
- content/events/2025-google-cloud-next.md
- content/events/2025-kubecon-eu-25.md
- content/events/2025-nab-show.md
- content/events/2025-wasmio-barcelona.md
Adds events to the homepage slider
> add upcoming events

- content/wasm-functions/faq.md
According to this page, this is also a limit: https://www.fermyon.com/wasm-functions
> Add App Size limit

- content/api/hub/ab_cookie_sample.md
- content/api/hub/ab_keyvalue_sample.md
- content/api/hub/ab_user_agent_sample.md
- content/api/hub/aggregate_json_sample.md
- content/api/hub/alter_response_headers_sample.md
- content/api/hub/autocomplete_sample.md
- content/api/hub/bulk_redirects_sample.md
- content/api/hub/early_hint_sample.md
- content/api/hub/get_list copy.md
- content/api/hub/key_value_tutorial.md
- content/api/hub/limit_access_sample.md
- content/api/hub/mysql_tutorial.md
- content/api/hub/object_storage_streaming_sample.md
- content/api/hub/read_post_sample.md
- content/api/hub/relational_db_tutorial.md
- content/api/hub/respond_with_other_site_sample.md
- content/api/hub/supabase_proxy_tutorial.md
- content/api/hub/template_http_empty copy.md
- content/api/hub/template_http_go copy.md
- content/api/hub/template_http_js copy.md
- content/api/hub/template_http_python copy.md
- content/api/hub/template_http_rust copy.md
- content/api/hub/template_http_ts copy.md
- content/api/hub/template_kv_explorer copy.md
- spin-redirecter/package-lock.json
- templates/home.hbs
> feat: add fwf examples

- content/wasm-functions/faq.md
Softening the language arund where FWF runs while in preview.
> Regional availability

- static/js/main.js
- static/js/src/modules/utils.js
@karthik2804 helped with this as a fix, which may just be temporary.
> Fix FWF quickstart tabs

- templates/home.hbs
Fixes https://github.com/fermyon/developer/issues/1518
> fix(templates): wasm-languages card link

- static/css/styles.css
- static/sass/developer-color-dark.scss
- static/sass/developer-content-home.scss
- static/sass/developer-responsive.scss
- templates/home.hbs
Styling changes - to fix #1496
> make project cards on landing page more clickable

- content/wasm-functions/aka-command-reference.md
> Update wasm-functions CLI reference for v0.4

- content/wasm-functions/app-linking.md
- content/wasm-functions/delete.md
- content/wasm-functions/deploy.md
- content/wasm-functions/get-logs.md
- content/wasm-functions/list-and-inspect.md
- content/wasm-functions/property-manager-integration.md
- content/wasm-functions/querying-linode-mysql.md
- content/wasm-functions/querying-postgresql.md
- content/wasm-functions/quickstart.md
- content/wasm-functions/stream-data-from-linode-object-store.md
- content/wasm-functions/supabase-cache-proxy.md
- content/wasm-functions/upgrade.md
- content/wasm-functions/using-cron-jobs.md
- content/wasm-functions/using-key-value-store.md
- templates/functions_sidebar.hbs
> Update wasm functions docs for v0.4 plugin

- content/wasm-functions/quickstart.md
- downloads/fwf_install.sh
This commit brings in the install script into the repo and also updates it to install the plugin from the registry so that users will be "badgered" by the spin plugins system to update when there is a new version.
> Bring the fwf quickstart install script into repo

- static/css/styles.css
- static/sass/developer-color-dark.scss
Fixes: #1555 
cc: @karthik2804 @flynnduism
> Fixed broken button in wasm function

- content/wasm-functions/github-actions.md
- templates/functions_sidebar.hbs
> adding gh actions tutorial to sidebar & fixing typo

- content/wasm-functions/github-actions.md
Closes https://github.com/fermyon/developer/issues/1537
> fix(docs): escape GH secret in yaml

- content/wasm-functions/changelog/changelog-aka-plugin-v043.md
- content/wasm-functions/changelog/changelog-aka-plugin-v044.md
> Add changelogs for v0.4.3 and v0.4.4

- content/wasm-functions/changelog/changelog-aka-plugin-v050.md
Ref https://github.com/fermyon/neutrino/issues/2511
https://github.com/fermyon/neutrino/releases/tag/plugin/v0.5.0
> docs(wasm-functions/changelog): add v0.5.0 entry
