content/spin/quickstart.md

Fix a typo `applicatin` -> `application`
Signed-off-by: goproslowyo <68455785+goproslowyo@users.noreply.github.com>

Fix `applicatin` typo in quickstart.md

---

content/spin/index.md

Fremoyn -> Fermyon
Signed-off-by: Aymeric Planche <aymeric.planche@gmail.com>

fix 2 typos in product name

---

content/spin/quickstart.md

Just a small PR to clean up the docs. When I was reading through this wasn't as clean as I thought it could be -- also enabled copy/pasting of the rustup comamnd (I think, just following the examples I'm seeing in the markdown here).
Thanks!
Signed-off-by: goproslowyo <68455785+goproslowyo@users.noreply.github.com>

Clean up the rustup add docs, enable copy/paste command

---

content/spin/configuration.md

Since Spin 0.6.0 is now released.
(I also fixed some capitalisation.)
Signed-off-by: itowlson <ivan.towlson@fermyon.com>

Remove canary note from Vault config docs

---

downloads/install.sh

- Removed the case where we say we don't support aarch64 on linux-gnu
- curl error is not only 'file not found' but any curl error, e.g. cannot write file output.

update install.sh to support Linux ARM64

---

content/spin/rust-components.md

The Rust Example code uses the /wildcard route instead of /hello. Updating the docs to match the code.
https://github.com/fermyon/spin/blob/013059cb7eda1189190fdec9fced86c9fc88867f/examples/http-rust-outbound-http/spin.toml#L22
Signed-off-by: Luke Berndt <lukekb@gmail.com>

Corrected the route to match example code

---

content/spin/rust-components.md

close #177 
This commit updates the Rust Redis examples from the Spin documentation to contain complete code samples, including imports.
Signed-off-by: Radu Matei <radu.matei@fermyon.com>

Update Rust Redis examples with complete code

---

downloads/install.sh

Although only informational, thought we'd bump the sample spin version strings to a more recent value.
[v0.8.0 is due to be released soon](https://github.com/fermyon/spin/pull/1092); we can wait for the release to finish before merging this

chore(install.sh): bump spin version strings to more recent value

---

content/spin/http-trigger.md

Update `routing` docs for `http-trigger.md` given the implementation of [spin#1109](https://github.com/fermyon/spin/pull/1109)
Welcome any wordsmith suggestions!
Signed-off-by: Brian H <brian.hardock@fermyon.com>

chore(docs): update routing docs

---

static/css/styles.css
static/sass/styles.scss

closes #281 
The changes due to this PR are 
From main:
With this PR:
Hides the TOC on smaller screen sizes
This fixes the issues of where a white scrollbar is rendered in dark mode.
Main:
Patch:

styling changes for TOC, codeblocks and setting theme

---

config/site.toml
templates/content_top.hbs

Review of our analytics config has led to recommendation that we  (i) use [GTM](https://tagmanager.google.com) across the board as the best method to study user patterns in our docs and between subdomains and (ii) we use the same script in each situation.
This PR replaces the prior GA4 embed with GTM. I've validated the new code with [the accompanying inspector tool ✅  ](https://dl3.pushbulletusercontent.com/AgetWW2a7CkOAMzl0Zt2De0HisB2jZ6S/dev-gtm.gif)
--
This doesn't impact the data - GTM will load GA4 (and cookie consent will be set via GTM as we did on fermyon.com)

replace prior google analytics 4 with gtm method

---

content/spin/install.md

Commencing the CLI Reference Docs and 0.9.0 installation nuances/usage.
Updating the Spin 0.9.0 CLI Reference and noticed one thing that got me thinking i.e. I noticed straight away that the login subcommand is not in the standard spin `--help`. There are evidently naturally expected changes; if there are any nuances that you would like explained in a certain way, please just leave a few notes in this PR's comments and I will return to working on this first thing next week.
For the most part this will just be a CLI Reference (listing all of the permutations of `--help` but any explanations that will assist users will be greatly appreciated (even in short note form below).

Preliminary commit to kick off CLI Reference Docs and 0.9.0 installation guide

---

content/spin/template-authoring.md

Adds a mention of template tags to the template authoring documentation. Wordsmithing welcome!

Update template authoring docs describing tags

---

.github/pull_request_template.md

Update PR checklist to prevent menu items linking to content before the doc's `date` of publication goes live.

---

static/js/highlight.min.js

For example, the Python syntax highlighting is not working on developer docs but is perfect on website. The file on website is larger and I assume supports more languages and is an updated version of highlighting.

Updating this file to match the main website's file

---

.gitignore

So we don't have log files getting in the way during commits and rebases.

Add logs/state directory to .gitignore

---

content/spin/writing-apps.md

Small nit. Files are not converted to an absolute path rather stay relative

Change absolute glob pattern resolution to stay relative

---

static/css/styles.css
static/sass/styles.scss

Small bug fix following #428 - the blockquotes in light mode were too dark to be legible. This PR corrects the color scheme.
before/after preview of change:

fix the blockquote light mode shading on docs

---

content/common/contributing-docs.md

A quick way to run lint tests over content during local writing and reviewing.

Document command to lint files (and not check all URLs after each local change)

---

content/spin/rust-components.md

Tested this out; `spin up` alone will print the data published from the Redis CLI (as per this example) without the need for `--follow-all`.
This is the only occurrence left; checked using `find content -type f -exec grep -H '\--follow\-all' {} \;`

Remove `--follow-all` from docs

---

content/spin/writing-apps.md

While we have docs on the [environment config provider](https://developer.fermyon.com/spin/dynamic-configuration.md#environment-variable-provider), it looks like setting component environment variables is no longer documented.

Add docs on component environment variables

---

content/spin/python-components.md

Correct spelling from `locahost` to `localhost`.

docs(python-components): correct spelling

---

.github/workflows/deploy-preview.yml

this is the PR that will add preview support for developer docs. Few gotchas:
- It can deploy previews only if PR is from a branch in `fermyon` org only. This is because of security considerations.
- we can deploy a max of 5 preview only right now.
- The action can delete old previews when it is out of limits (disabled right now), we should probably enable it. Pls let me know
- The action deletes the preview when the PR is closed. (merged or not).
- It currently uses browser automation to do the cloud login
- It is currently using a Github account I have setup using one of my personal domain (I am working on configuring a Fermyon account for this. will update the secrets in repo once we are ready for that.)

Trying out preview deployment from fermyon org

---

content/spin/writing-apps.md

Fix missing = in environment variable example

---

.build/check-broken-links.sh

Follow-up to https://github.com/fermyon/developer/pull/443
Although the updated test passed on the PR as well as [my fork](https://github.com/vdice/developer/actions/runs/4599007771/jobs/8123833996), we're seeing a timeout failure after merging: https://github.com/fermyon/developer/actions/runs/4598971134/jobs/8123874389
Indeed, perhaps my reducing from 60s to 10s was a bit to aggressive.  This bumps the timeout (to wait for the local version of the website to come up) back up to 60s.

fix(check-broken-links.sh): increase timeout to 60s

---

content/spin/contributing-spin.md

Flag lints and signing in Spin contribution docs

---

content/cloud/changelog/custom-fermyon-subdomain.md

Added an inline URL because the changelog preview talks about "below" but the preview page does not show anything below.

Links not showing in preview - added inline URL to solve

---

content/common/contributing-docs.md

This is a great suggestion from @karthik2804 to track the use of class names in the docs.

Add centralized list of class names

---

content/cloud/github-actions.md

This PR addresses Issue #563 to by correcting adding `npm install` to the TypeScript for deploying with Github Actions.

Updating GH Actions TypeScript example

---

content/spin/writing-apps.md
templates/bartholomew_sidebar.hbs
templates/cloud_sidebar.hbs
templates/spin_sidebar.hbs

Updated sidebar menu items for Cloud, Spin and Bartholomew:
Each uses the same menu terminology i.e. "Get Started"
There are some additional (unique to each project) menu labels but after this update, the shared labels are ordered. For example shared menu labels between each project now fall in the same order i.e. "Get Started" -> "Application" -> "Tutorials" -> "References" -> "Contributing".
Also shared sub-menu labels (pages) terminologies like "Templates" all fall under the menu label of "Tools"; whereas before pages and menu labels were not 100% aligned (across different projects).
We will soon use accordion (collapsable) menus, at which point the top-level menu label becomes more important.

Align menu names across projects

---

content/bartholomew/contributing-bartholomew.md
content/bartholomew/index.md
content/bartholomew/markdown.md
content/bartholomew/quickstart.md
content/cloud/changelog/cloud-key-value.md
content/cloud/changelog/custom-fermyon-subdomain.md
content/cloud/changelog/gh-actions-spin-deploy.md
content/cloud/changelog/request-metrics-in-cloud.md
content/cloud/data-postgres.md
content/cloud/data-redis.md
content/cloud/faq.md
content/common/cli-reference.md
content/common/contributing-docs.md
content/spin/api-guides-overview.md
content/spin/cache.md
content/spin/distributing-apps.md
content/spin/dynamic-configuration.md
content/spin/kv-store-tutorial.md
content/spin/language-support-overview.md
content/spin/plugin-authoring.md
content/spin/python-components.md
content/spin/spin-oci.md

This is an update of the `bartholomew.wasm` file in the modules directory to implement fixes for relative vs absolute URLs and also improvements i.e. allowing dynamic URLs (so a user is not thrust over to the `common` section's menu if clicking on a shared document that exists in the common area).

Upgrade of Bartholomew Wasm Module

---

.github/workflows/build.yml

The version of Bartholomew in the build/workflow config can be at the latest version as new versions of Bartholomew are released.

Update Bartholomew in workflow, to lastest

---

content/spin/go-components.md
content/spin/http-outbound.md
content/spin/javascript-components.md
content/spin/python-components.md
content/spin/rust-components.md

First draft to replace random API endpoint:

Random API Update - Ready for approval

---

templates/main.hbs

This adds the project sidebar when failing to find a page on particular projects
before
after

add sidebar when 404ing on particular project

---

.github/workflows/deploy.yml

Pins the `spin` CLI version in the deploy.yml workflow to the latest v1.2.1 version.
Closes https://github.com/fermyon/developer/issues/610

chore(deploy.yml): pin spin to latest v1.2.1 version

---

content/spin/install.md
content/spin/quickstart.md
downloads/install.sh

Updates the install script to install default templates and all language plugins and associated documentation.
Note: This can set a precedent for installations of spin to come with this set plugins and templates. For example, future package manager installations can follow this practice. 

Update install script to install default plugins and templates

---

.github/workflows/deploy.yml

- Use the pushed image digest for the oci ref passed to the nomad job

ci(deploy.yml): use digest for oci_ref

---

content/spin/kubernetes.md

Use wasmtime-spin-v1 as the runtimeClass to match the containerd shim version v1 across the document.

fix: inconsistency in runtimeClass naming in k8s docs

---

content/spin/http-outbound.md
content/spin/kv-store-api-guide.md
content/spin/redis-outbound.md

Consistently link Go Packages for API docs, but do not use badge

---

content/spin/install.md
downloads/install.sh

I didn't update the other references to what the install script installs to say it also installs the cloud plugin. It didn't seem necessary to state since if not preinstalled it will be automatically installed later
DO NOT MERGE until after the 1.3 spin release

Install cloud plugin in install script

---

content/cloud/cloud-plugin.md
content/spin/contributing-docs.md
templates/cloud_sidebar.hbs

Cloud commands
We will likely want to link to the cloud plugin blog from here. 
~Draft PR to see what folks think about having this added page in cloud to describe the `spin cloud` subcommands.~
~For some reason, the tabs are not rendering correctly :/~
~Note: Made up the existence of a cloud plugin `v0.1.1` that has an unhidden variables command. Likely we will actually replace this version~ removed
~TODO: add definition of what supported spin version for each cloud plugin version~

Add Cloud Command Reference page

---

content/cloud/delete.md
content/cloud/variables.md
templates/cloud_sidebar.hbs

Tutorial for new configuration variables feature.
References the cloud command reference page, so should be merged after https://github.com/fermyon/developer/pull/681
- [x ] The `title, `template`, and `date` are all set

Add a configuration variables tutorial

---

content/cloud/cloud-plugin.md

I indexed but did not add the variables subcommands. this adds them

fix(cloud): add variables subcommands to cloud command reference

---

content/cloud/faq.md
content/cloud/variables.md
content/spin/api-guides-overview.md
content/spin/language-support-overview.md
content/spin/variables.md
templates/spin_sidebar.hbs

We have been missing an API for Config Variables. I added one and reference it from the FAQ page.
The examples in the guide are more verbose than other guides. Let me know it they are not minimal enough. I like the idea of having working handles. 

Add an API Guide for Configuration Variables

---

content/spin/quickstart.md

Add deployment step to Spin quickstart

---

content/cloud/cloud-command-reference.md
content/cloud/cloud-plugin-reference.md
content/cloud/variables.md
content/spin/cli-reference.md
content/spin/running-apps.md
templates/cloud_sidebar.hbs

This PR picks up from here: https://github.com/fermyon/developer/pull/698 to add the 1.3 CLI reference, now with the Cloud Plugin having it's own reference, and links between.
Also a bit of restructuring the headers to mimic the commands in the CLI.

Refactor cli

---

.github/workflows/build.yml

We [recently updated to Bartholomew 0.8.0](https://github.com/fermyon/developer/commit/c13d9859625287e33876b1fa5c803c4f75f17938) and removed the common folder etc. This PR is to just update/sync the version of Bart in the GH workflows with what is being used in the developer site's module section.

Update build.yml to sync with latest bart version being used

---

content/spin/variables.md

Relating to https://github.com/fermyon/spin/issues/1628

Make link from variables API guide to config page more prominent

---

.github/workflows/build.yml
.github/workflows/deploy-preview.yml
.github/workflows/deploy.yml
README.md
package.json
spin.toml

- Adds build and watch config to the main bartholomew component for the website app
- Updates CI to run `spin build` (also aligns build.yml to install spin via the [setup action](https://github.com/fermyon/actions#install-spin-cli-and-plugins---fermyonactionsspinsetupv1) like the others)

ci(*): add/use build and watch config

---

content/spin/cache.md
content/spin/distributing-apps.md
templates/spin_sidebar.hbs

Fixes #680.
@tpmccallum I moved a couple of sentences from the "registry cache" page to the "running published applications" section, and moved the cache layout diagram to give more prominence to the explanation.  I'm happy to revert those changes if you prefer them as they were.

Spin internal data layout

---

content/spin/plugin-authoring.md

Plugin environment variables

---

content/spin/cli-reference.md

Add Spin v 1.4 CLI Reference

---

content/cloud/faq.md
content/spin/api-guides-overview.md
content/spin/dynamic-configuration.md
content/spin/kv-store-api-guide.md
content/spin/language-support-overview.md
content/spin/rdbms-storage.md
content/spin/sqlite-api-guide.md
templates/spin_sidebar.hbs

~This is extremely WIP at the moment - just punting it up so it's tracked.~ This is not as WIP as it used to be - it probably needs some redrafting but should be ready to review.
`sqlite-api-guide.md` has a new menu link but thankfully the frontmatter's date in the `sqlite-api-guide.md` is before today's date so this won't be an issue.

SQLite documentation

---

content/spin/contributing-spin.md

docs for https://github.com/fermyon/spin/pull/1603

Add `cmake` to list of Spin build dependencies in contributing docs

---

content/spin/quickstart.md

Related content:
https://github.com/fermyon/developer/issues/520
https://github.com/fermyon/developer/issues/222

added go env variable in the doc

---

content/spin/kubernetes.md

after a ton of debugging i finally found out why my rust project won't run, and it's due to a lower version of Spin on AKS.
Repro:
Generate a spin rust http project with `spin new` and deploy it to AKS following the current guide
Every http request returns a 500 status code, and no logs are produced. Downgrading to the supported spin sdk version fixes this for rust
> #730  I notice that in this [article](https://developer.fermyon.com/spin/kubernetes), it uses the wasmtime-spin-v1 runtime class to refer to the AKS node's runtime handler. However, this runtime handler is using a older version of Spin v0.3.0. I would recommend to this to wasmtime-spin-v0-5-1 which uses the v0.5.1 spin shim binary that uses v1.0 spin.
ref: …

add info for AKS lower spin version

---

config/site.toml

Closes https://github.com/fermyon/developer/issues/578
I am a little perplexed because currently (without this change), the developer documentation correctly provides the URL to the favicon in the `head` of the HTML pages already.
This update seems more correct than the `site.toml` linking to a folder other than `icon` (where the icons live). But any advice would be appreciated. @flynnduism do you have any thoughts on this?

Update location of favicon in site's config

---

content/spin/sqlite-api-guide.md

Fix old type name in Rust SQLite docs

---

content/cloud/cloud-command-reference.md
content/spin/cli-reference.md

Add Spin Cloud SQLite Reference (v0.1.2)

---

content/cloud/fermyon-cloud.md
content/spin/contributing-docs.md

Added the starting instructions on how to preview on localhost to contributing documentations page

---

content/api/hub/contributing.md

Small correction to where to find the Spin Up Hub files.

Fix path reference in contrib guide for Spin Up Hub

---

content/spin/running-apps.md

Clarification on how workdir impacts the watch specification in spin.toml.

Specify watch and workdir relationship in spin.toml

---

content/api/hub/plugin_check_for_update.md

This PR adds the `check-for-update` plugin to the Spin Hub.
- [] The `title, `template`, and `date` are all set

Add check-for-update plugin to Spin Hub

---

content/spin/kv-store-api-guide.md

This captures how things behave at js2wasm 0.5.1 / spin-sdk 0.5.0.
@karthik2804 I don't know if the behaviour of `getJson` in particular is considered correct. If this doesn't seem right and you plan to change it, we can hold off on these docs.

Document error behaviour of JS KV get/getJson

---

content/spin/go-components.md
content/spin/javascript-components.md
content/spin/python-components.md

Fix KV language and reference in language guides

---

content/spin/http-outbound.md

Fix Python outbound HTTP fragment

---

content/api/hub/contributing.md

Fixed two tiny typos

---

content/spin/javascript-components.md

This PR removes an unnecessary line of code from the outbound HTTP sample for JavaScript.

Remove unnecessary line of code from outbound http sample

---

content/spin/sqlite-api-guide.md

This is so that a user understands that deploying to Cloud uses different subcommand option.

Respond to a suggestion from user (link from Spin to Cloud)

---

content/spin/contributing-spin.md

Removing from Spin in https://github.com/fermyon/spin/pull/1728

Remove cmake from Spin build dependencies

---

spin.toml

The current `build.watch` configuration:
* Rebuilds the index files in `static`
* Depends on multiple directories including `static`
This causes `spin watch` to go into an infinite loop as the build updates the index files in static, which triggers a rebuild, which updates the index files in static, which...
The only actual inputs to the indexes are under `content`, so this is the only directory we need to watch _for rebuild_.
(Yes, other directories require a reload, i.e. restart `spin up`.  That will still happen because `spin watch` considers the `files`.  But these don't require a re-run of the index build commands.)

Trigger index rebuild only when content changes

---

content/api/hub/sample_hugo.md

This PR adds the [`hugo-spin`](https://github.com/ThorstenHans/hugo-spin) template repository to the Spin Up Hub. 
fixes #803 

Add hugo-spin template repository to Spin Up Hub

---

content/spin/rust-components.md

This PR adds a small note about the Rust Spin SDK documentation which is currently available at https://fermyon.github.io/rust-docs/spin/main/spin_sdk/index.html.

Add link to the Rust Spin SDK documentation

---

spin-up-hub/src/components/PreviewModal.vue

fix verified badge placement on preview modal

---

downloads/install.sh

Installs canary plugins when flag is specified and warns that templates must be manually modified to target canary SDKs.
~Note: python SDK canary is currently behind latest. We should amend that before we merge this.~ The canary artifacts are updated despite the canary release looking old

fix(install): Update install script to install canary plugins

---

content/cloud/serverless-ai.md

The [Update install script to install canary plugins](https://github.com/fermyon/developer/pull/863) PR now makes the Spin installation script install the required canary plugins automatically (when a user provides the `-v canary` option during their Spin installation).
Below is the output after using the newly updated Spin installation script (which attends to canary plugins automatically):
```bash
$ curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash -s -- -v canary
// -- snip --
$ ./spin plugins list  
check-for-update 0.0.1
check-for-update 0.1.0
cloud 0.1.0
cloud 0.1.1
cloud 0.1.2
cloud 0.1.2post.1693590746 [installed]
js2wasm 0.1.0
js2wasm 0.2.0
js2wasm 0.3.0
js2wasm 0.4.0
js2wasm 0.5.0
js2wasm 0.5.1
js2wasm …
```

Revert instructions because installation script handles canary plugins now.

---

content/api/hub/template_qwik_frontend.md

add Qwik frontend template

---

content/spin/language-support-overview.md
content/spin/sqlite-api-guide.md

TinyGo SQLite will be released in Spin 1.5

Add TinyGo SQLite to the API guide

---

content/api/hub/sample_coffee_shop_in_dapr_k3d.md

The content of the series blog posts:
- [Demo scenario with coffeeshop application](https://dev.to/thangchung/webassembly-docker-container-dapr-and-kubernetes-better-together-part-1-demo-scenario-with-coffeeshop-application-28i2)
- [Build and run the coffee shop backend services](https://dev.to/thangchung/webassembly-docker-container-dapr-and-kubernetes-better-together-part-2-build-and-run-the-coffee-shop-backend-services-3c0e)
- [Daprize the coffee backend services](https://dev.to/thangchung/webassembly-docker-container-dapr-and-kubernetes-better-together-part-3-daprize-the-coffee-backend-services-239n)
- [Package and deploy to Kubernetes](https://dev.to/thangchung/webassembly-docker-contain …

Updating Spin Up Hub with sample_coffee_shop_in_dapr_k3d

---

downloads/install.sh

I was finally able to reproduce an error that has been flagged in an issue. This update closes https://github.com/fermyon/developer/issues/748 by adding a new step in the installer, which checks to see if a `spin` item is in the way of the installer succeeding (before the user’s end expends any resources on downloading the tarball).

Add a check to see if a `spin` item is in the way of the installer succeeding (before we even download the spin tarball)

---

content/spin/manifest-reference.md

Add `watch` section to manifest reference

---

content/api/hub/contributing.md

Fixes #885.
Based on https://github.com/fermyon/developer/issues/849#issuecomment-1713145311

Add required build info to hub contributing guide

---

content/cloud/data-postgres.md
content/cloud/rest-api.md
content/cloud/variables.md
content/spin/build.md
content/spin/contributing-docs.md
content/spin/http-trigger.md
content/spin/javascript-components.md
content/spin/kv-store-tutorial.md
content/spin/managing-plugins.md
content/spin/managing-templates.md
content/spin/python-components.md
content/spin/quickstart.md
content/spin/redis-trigger.md
content/spin/running-apps.md
content/spin/rust-components.md
content/spin/serverless-ai-api-guide.md
content/spin/serverless-ai-tutorial.md
content/spin/spin-application-structure.md
content/spin/variables.md
content/spin/writing-apps.md

Noticed a bunch of code blocks that were not using selective copy, no copy as intended.
Rule of thumb that I am following is:
- if a code block has `$` at the start of the commands and you just want the lines prefixed with `$` to be copied to the user’s clipboard (with the `$` magically removed so when the user pastes the commands they work in their terminal; i.e. no `$` persists) then use `<!-- @selectiveCpy —>` before the code block
- if a code block has content in it that you don’t want the user to easily “click” to copy i.e. some output like `befunged output is returned.` then use the `<!-- @nocpy —>`
- if a code block has usable code such as Rust or Javascript and you would like to make it possible for the user to “click” and obtain that code block’s content’s in their clipboard for …

Update selective copy

---

content/api/hub/contributing.md
content/spin/contributing-docs.md

Remove copy symbols/icons from codeblocks, because copy does not work on Spin Hub.

---

content/spin/dynamic-configuration.md

Should we also add something about an example implementation being the `spin-cloud-gpu` plugin?

add llm remote_http option

---

content/cloud/deployment-concepts.md

This is tied to the release of Cloud Plugin 0.3.0.

Update docs for Bindle to OCI

---

content/spin/ai-sentiment-analysis-api-tutorial.md

Replaced `all-minikm-16-v2` with `all-minilm-l6-v2`
- notice the `k` turns into an `l`
- notice the `1` turns into an `l`

Fix typo in ai-sentiment-analysis-api-tutorial.md

---

content/api/hub/sample_crossword_helper.md

The crossword helper on the Hub currently has the title "news summariser".

Fix title of crossword helper hub

---

content/api/hub/sample_view_counter.md

https://dev.to/technosophos/storing-state-between-serverless-requests-with-typescript-and-spin-3p3i

Add view counter example

---

content/spin/v2/http-trigger.md
content/spin/v2/rust-components.md
content/spin/v2/triggers.md
templates/spin_sidebar.hbs

This limits itself to inbound HTTP.  I need to do a bit more research to write about outbound HTTP but wanted to get something out there.  There are also other v1 manifests on the Rust language page which I did not get to in this PR; I will pick those up when I write about outbound HTTP, or as part of a general manifestation pass.
~Also this need to move to the v2 folder - I jumped the gun...~  This is v2-ified.  There is a new page, v2/triggers.md, which will need to be added to the v2 TOC once we figure that out - for the time being I left the TOC entry commented out.

HTTP handling in Spin 2

---

content/spin/v2/kv-store-api-guide.md
content/spin/v2/redis-outbound.md
content/spin/v2/rust-components.md

I'm sorry Tim this was meant to be Redis but it wandered off into KV and I got myself confused.  Hopefully you can make sense of it
✅ content/spin/v2/kv-store-api-guide.md
tpmccallum@192-168-1-4 developer % bart check content/spin/v2/redis-outbound.md 
✅ content/spin/v2/redis-outbound.md
tpmccallum@192-168-1-4 developer % bart check content/spin/v2/rust-components.md 
✅ content/spin/v2/rust-components.md

Redis and stuff

---

content/spin/v2/http-outbound.md
content/spin/v2/rust-components.md

There is probably more to do on this but it's not fully working right now... _grin_  I understand Python and JS are not changing on day one, and will likely get support via componentise-blah tools rather than the current plugins; I am not 100% sure about Go but _guess_ it is staying the same for now...?
✅ content/spin/v2/http-outbound.md
✅ content/spin/v2/rust-components.md

Outbound HTTP

---

content/spin/v2/http-trigger.md
content/spin/v2/rust-components.md

✅ content/spin/v2/http-trigger.md 
✅ content/spin/v2/rust-components.md

Update Rust HTTP to latest SDK

---

content/spin/v2/http-trigger.md
content/spin/v2/redis-trigger.md

✅ content/spin/v2/http-trigger.md
✅ content/spin/v2/redis-trigger.md

Redis triggers and HTTP updates for v2

---

content/spin/v2/build.md
content/spin/v2/running-apps.md
content/spin/v2/spin-application-structure.md

✅ content/spin/v2/build.md
✅ content/spin/v2/running-apps.md
✅ content/spin/v2/spin-application-structure.md

Rest of Applications section to v2

---

content/spin/v2/api-guides-overview.md
content/spin/v2/http-outbound.md
content/spin/v2/kv-store-api-guide.md
content/spin/v2/rdbms-storage.md
content/spin/v2/redis-outbound.md
content/spin/v2/serverless-ai-api-guide.md
content/spin/v2/sqlite-api-guide.md
content/spin/v2/variables.md

There were a few modifications to samples, and I am a bit at sea with which languages have updated how.  Reasonably confident with the Rust changes but would really appreciate heightened diligence on this one, I am very concerned I have missed something or messed something up but cannot see what
✅ content/spin/v2/api-guides-overview.md
✅ content/spin/v2/http-outbound.md
✅ content/spin/v2/kv-store-api-guide.md
✅ content/spin/v2/rdbms-storage.md
✅ content/spin/v2/redis-outbound.md
✅ content/spin/v2/serverless-ai-api-guide.md
✅ content/spin/v2/sqlite-api-guide.md
✅ content/spin/v2/variables.md

Update API guides to v2

---

content/spin/v2/http-outbound.md

✅ content/spin/v2/http-outbound.md

Mention some of the new outbound HTTP helpers

---

content/spin/v1/index.md
content/spin/v1/install.md
content/spin/v1/quickstart.md
content/spin/v2/index.md
content/spin/v2/install.md
content/spin/v2/quickstart.md

✅ content/spin/v1/install.md
✅ content/spin/v1/index.md
✅ content/spin/v1/quickstart.md
✅ content/spin/v2/install.md
✅ content/spin/v2/index.md
✅ content/spin/v2/quickstart.md

added SUH cards to developer docs

---

content/spin/v2/http-trigger.md
content/spin/v2/redis-trigger.md

We mention the Spin WIT files in a couple of places.  In https://github.com/fermyon/spin/pull/2058 these changed location to remove the `preview2` directory.  This fixes the references to the new paths.
For future we should consider whether to permalink (no risk of link breakage but could leave us pointing at an out-of-date commit with no broken link error to warn us) or continue to use the `main` link (always up to date but could cause links to break during unrelated PRs).

Fix for Spin repo moving WITs

---

content/cloud/changelog/serverless-ai-open-beta.md
content/spin/v1/index.md
content/spin/v1/quickstart.md
content/spin/v2/index.md
content/spin/v2/install.md
content/spin/v2/quickstart.md

quick card typo and v1 vs v2 cleanup

---

content/spin/v2/rust-components.md

The example code does not currently work as expected (i.e., it does not return a response with a body). This fixes that.

Fix response body for outbound Rust HTTP example

---

content/spin/v2/go-components.md
content/spin/v2/http-outbound.md
content/spin/v2/http-trigger.md
content/spin/v2/kv-store-api-guide.md
content/spin/v2/language-support-overview.md
content/spin/v2/rdbms-storage.md
content/spin/v2/redis-outbound.md
content/spin/v2/redis-trigger.md
content/spin/v2/rust-components.md
content/spin/v2/serverless-ai-api-guide.md
content/spin/v2/sqlite-api-guide.md
content/spin/v2/variables.md

Although we link specific Rust and Go SDK members, there are no prominent links to the published SDK docs as a whole.  This PR adds SDK links (either whole-SDK or the specific subset) at the top of each language tab so that users who just want the reference can dive across, hopefully without it getting too much in the way of readers who want to get a bit more explanation!
Examples of how it looks:
**Language support overview**
**Language guide**
**Trigger docs**
**API guides**
I've raised issues for JS and Python reference docs and the idea is to link those in a consistent style when we have them.

Link SDK reference docs where available

---

content/spin/v2/rust-components.md

Instead of pushing the user towards the http crate, we prefer the built-in SDK http types. However, we also include a section on using the `http` crate should the user wish to do so.
This works in tandem with https://github.com/fermyon/spin/pull/2065

Prefer usage of SDK types in Rust http examples.

---

content/api/hub/sample_http_auth_middleware.md

Adding http-auth-middleware to SUH

---

content/spin/v2/http-trigger.md
content/spin/v2/javascript-components.md
content/spin/v2/kv-store-api-guide.md
content/spin/v2/language-support-overview.md
content/spin/v2/rdbms-storage.md
content/spin/v2/redis-outbound.md
content/spin/v2/serverless-ai-api-guide.md
content/spin/v2/sqlite-api-guide.md
content/spin/v2/variables.md

(also contains a couple of unrelated typo fixes because the spell checker was yelling at me)

Add links to JavaScript SDK reference

---

content/spin/v2/http-outbound.md
content/spin/v2/http-trigger.md
content/spin/v2/kv-store-api-guide.md
content/spin/v2/language-support-overview.md
content/spin/v2/python-components.md
content/spin/v2/rdbms-storage.md
content/spin/v2/redis-outbound.md
content/spin/v2/redis-trigger.md
content/spin/v2/serverless-ai-api-guide.md
content/spin/v2/sqlite-api-guide.md
content/spin/v2/variables.md

Also makes SDK reference links more consistent.

Add Python SDK reference links

---

content/api/hub/sample_ts_router_post.md

Add TS example of handling POST data from a router.

---

scripts/timed_publish.rhai

Content can be wrapped around with the following tag in templates to enable displaying them only once a preset time is past. 
```
{{#if (timed_publish "2023-07-25T17:26:00Z" env.PREVIEW_MODE)}}
// Content
{{/if}}
```

add script to enable publish by time

---

content/spin/v2/kubernetes.md

- Bumps to latest [v0.10.0](https://github.com/deislabs/containerd-wasm-shims/releases/tag/v0.10.0) version of the shim
- Updates RuntimeClassName to `wasmtime-spin` per https://github.com/deislabs/containerd-wasm-shims/blob/main/README.md?plain=1#L89 and https://github.com/chrismatteson/spin-plugin-k8s/blob/main/k8s#L138
- Updates Spin/shim version matrix
Fixes https://github.com/fermyon/developer/issues/1053

docs(kubernetes.md): shim version bumps/updates

---

content/spin/v2/kv-store-api-guide.md

Fix some errors/omissions in K/V API guide

---

content/cloud/noops-sql-db.md

Add `component.example` to more accurately reflect the config of v2.

---

content/cloud/noops-sql-db.md

Add example of using file to populate cloud database tables and execute sql

---

content/api/hub/sample_bookmarker.md
content/api/hub/sample_jinja2.md
content/api/hub/sample_kv_in_python.md
content/api/hub/sample_router.md

The Build tests are failing on an unrelated broken link.
This all LGTM.

adding 4 Python SUH cards

---

spin-up-hub/index.html

Small edit, to enable [Plausible Goal metrics](https://plausible.io/docs/custom-event-goals). We added targeted event classes to see no. of clicks etc, but the JS include needs to be updated to get this working properly.

enable goal metrics in spin up hub

---

content/cloud/linking-applications-to-resources-using-labels.md

- Fixes ordering in `spin cloud link/unlink sqlite` examples

docs(linking-apps): fix link/unlink sqlite command order

---

content/spin/v2/language-support-overview.md

✅ content/spin/v2/language-support-overview.md

Make link to SDK reference more prominent

---

content/api/hub/sample_ollama.md

This sample showcases Ollama api implementation using spin.

ollama api sample added

---

content/api/hub/template_docusaurus.md

This PR adds the [spin-docusaurus](https://github.com/VamshiReddy02/spin-docusaurus) template repository to the Spin Up Hub. I'm sorry for closing my Last PR because of some technical issues. All the requested changes have been made. please let me know if there are any further changes to be made. 
Fixes issues: #801 
✅ content/api/hub/template_docusaurus.md

Created docusaurus-spin template repository to Spin Up Hub

---

content/api/hub/sample_11ty.md

This PR adds the [spin-11ty](https://github.com/VamshiReddy02/spin-11ty) template repository to the Spin Up Hub.
Fixes issues: #802 

Add 11ty-spin template repository to Spin Up Hub

---

content/api/hub/sample_bookmarker.md

I renamed the title of "Bookmarker: An AI-powered Bookmarking Web App" to "AI Bookmarker: Smart Bookmarking Web App" because it overlapped with tags that did not look good. It's a temporary fix for now.
Before changes:
After changes:

Fixed the AI bookmarker card title

---

content/api/hub/sample_redirect.md

Fixed "qr code" problem in hub search

---

content/spin/v2/template-authoring.md

Addresses https://github.com/fermyon/spin/issues/2205.
(The change is true for both Spin 1 and Spin 2, but I added it only to Spin 2 because my understanding is that Spin 1 content is considered archived unless circumstances warrant, and this... didn't seem to warrant.  If we are containuing to maintain Spin 1 copies then I can easily add it there too.)

More info about template syntax

---

spin-up-hub/src/components/ContentFilter.vue

fixes #1107 
Weird bug in Chrome on macos where a `<a>` tag without a `href` was causing the page to reload. We should potentially not be using the `a` tag where it is not a link but that involves stylistic changes which can be done in a future PR. 
cc: @flynnduism

add empty href tag to fix macos chrome bug

---

content/bartholomew/contributing-bartholomew.md
content/spin/v1/rust-components.md
content/spin/v2/rust-components.md

Fixes #1114.
In this PR I've opted to remove the broken links altogether, because the moved pages seemed more scary than helpful to someone just wanting to install or use the target.  If other folks think the links did add value, I can restore them to the new location.

Remove links to Rust target spec docs

---

static/css/styles.css
static/sass/styles.scss

fix #1122 
This PR increases the font weight of the links in the content to make them a bit more bold and distinguishable.

increase font weight on links

---

content/spin/v1/http-trigger.md
content/spin/v1/redis-trigger.md
content/spin/v1/variables.md

These files were removed from Spin `main` in November of last year.  No idea how the links only failed today.

Updated v1 links removed from main ages back

---

content/cloud/custom-domain.md

Update custom domain docs to mention limitations around additional DNS records.

---

content/cloud/custom-domain.md
content/cloud/custom-domains-tutorial.md
content/cloud/faq.md

$ bart check content/cloud/faq.md
✅ content/cloud/faq.md
$ bart check content/cloud/custom-domain.md
✅ content/cloud/custom-domain.md
$ bart check content/cloud/custom-domains-tutorial.md 
✅ content/cloud/custom-domains-tutorial.md

Updating limitations of custom domains

---

content/api/hub/template_nuxt.md

This PR adds the [spin-nuxtjs](https://github.com/VamshiReddy02/spin-nuxt) template repository to the Spin Up Hub. Please let me know if there are any further changes to be made. 
Fixes issue: #800 
And also Happy New Year to the Fermyon team and its community.

Created Nuxtjs-spin template repository to Spin Up Hub

---

content/spin/v2/go-components.md

Update Go Components page - to align with 2.1.0

---

static/css/styles.css
static/sass/developer-color-dark.scss

Fixes: #1131 
I made some changes, please once check and let me know if any further changes need to be made

Fixing the hover effect issue on footer links on the spin-up hub page

---

content/cloud/cloud-command-reference.md

✅ content/cloud/cloud-command-reference.md

add cloud command reference for v0.6.0

---

content/spin/v2/http-outbound.md

Fix error on Rust example and test

---

content/api/hub/template_kv_explorer.md
content/spin/v1/ai-sentiment-analysis-api-tutorial.md
content/spin/v2/ai-sentiment-analysis-api-tutorial.md

✅ content/api/hub/template_kv_explorer.md
✅ content/spin/v1/ai-sentiment-analysis-api-tutorial.md
✅ content/spin/v2/ai-sentiment-analysis-api-tutorial.md

Update KV explorer docs for latest release

---

content/spin/v1/http-outbound.md
content/spin/v1/python-components.md
content/spin/v1/redis-outbound.md
content/spin/v2/http-outbound.md
content/spin/v2/http-trigger.md
content/spin/v2/key-value-store-tutorial.md
content/spin/v2/kv-store-api-guide.md
content/spin/v2/language-support-overview.md
content/spin/v2/python-components.md
content/spin/v2/redis-outbound.md
content/spin/v2/redis-trigger.md
content/spin/v2/serverless-ai-api-guide.md
content/spin/v2/sqlite-api-guide.md
content/spin/v2/variables.md

Fix Python SDK and WIT links

---

content/cloud/spin-vs-code-extension.md
content/spin/v1/contributing-docs.md
content/spin/v2/contributing-docs.md
content/spin/v2/http-trigger.md
content/spin/v2/redis-trigger.md
content/spin/v2/variables.md

The Spin folks moved the WITs _again!_  While fixing those I ran into some relative paths in the Spin docs that had become broken and were for some reason not being included in the summary, so fixed them too.
(There is something up with the animal facts API at the moment and I can't tell what, so this doesn't fix that!)

Fix broken links

---

content/spin/v2/managing-plugins.md

tpmccallum@tpmccallum:~/developer$ bart check content/spin/v2/managing-plugins.md 
✅ content/spin/v2/managing-plugins.md

Add --all option to plugins docs and also explain downgrading with an example

---

content/wasm-languages/zig.md

Fixes https://github.com/fermyon/developer/issues/1194
$ bart check content/wasm-languages/zig.md 
✅ content/wasm-languages/zig.md

Update Zig page

---

content/spin/v2/manifest-reference.md

Fixes https://github.com/fermyon/developer/issues/1191

Add example manifest

---

content/spin/v2/quickstart.md

Quickstart page missed a closing code block.

Add missing code block close

---

content/spin/v1/key-value-store-tutorial.md
content/spin/v2/key-value-store-tutorial.md

fixing the key value tutorial urls in the md files for both v1 and v2 md docs

fixing the key value tutorial urls in the md files

---

content/cloud/faq.md

Minor change to clarify FC doesn't support service chaining ATM

clarifying service chaining support in FC

---

content/spin/v2/http-outbound.md
content/spin/v2/manifest-reference.md
content/spin/v2/rdbms-storage.md
content/spin/v2/redis-outbound.md
content/spin/v2/redis-trigger.md

Some manifest fields can now include variables

---

content/spin/v2/cli-reference.md

Create new 2.4 code tabs for Spin Cli Reference to populate with new values:
Possibly `spin up --cache-dir` https://github.com/fermyon/spin/commit/731bc1ff7a2a43e3708b79b0477e8f4dbf1f9dfc
and (https://fermyon.slack.com/archives/D03NAM1JS4R/p1712202575784749)
`spin new --no-vcs` https://github.com/fermyon/spin/commit/0c05b2af3bf39f58d6f0537614bf704079897f7f
Bart check:
Local preview:

Create new 2.4 tabs to populate

---

content/wasm-languages/dart.md

Drop reference to discontinued `wasm` package.
Updated link to Flutter support

Update Dart docs

---

content/api/hub/pattern_aggregates.md
content/api/hub/pattern_long_running_jobs_over_http.md

This commit adds "Long-Running Jobs over HTTP" and "Aggregate Pattern" to the Hub

Add new enterprise architectures and patterns to the Spin Up Hub

---

content/spin/v2/python-components.md
content/wasm-languages/python.md

Fixes https://github.com/fermyon/developer/issues/1254
Related https://github.com/fermyon/spin-python-sdk/pull/99

Use Spin SDK 3.1.0 and Componentize-Py 0.13.3

---

content/spin/v2/rust-components.md

Fixes https://github.com/fermyon/developer/issues/1253
This has already been documented, but it is not easily found. Therefore, this PR has been created to hoist that page to the surface. And still leave the other search results intact.
Before:
After:
This takes the user to the example shown below:

Add improved search for `async` in Rust documentation.

---

content/spin/v2/contributing-docs.md

As mentioned in #1237 the `timeout` binary must be installed on the machine to test for broken links. 
With this PR additional instructions are added to the **Contributing to Docs** page, to list it as dependency and explain how to install `coreutils` on macOS using Homebrew

docs: Explain how to install coreutils on macOS to test broken links

---

content/spin/v2/contributing-spin.md
content/spin/v2/rust-components.md

Add Rust version dynamically

---

content/spin/v1/ai-sentiment-analysis-api-tutorial.md
content/spin/v1/serverless-ai-api-guide.md
content/spin/v1/serverless-ai-hello-world.md
content/spin/v2/ai-sentiment-analysis-api-tutorial.md
content/spin/v2/serverless-ai-api-guide.md
content/spin/v2/serverless-ai-hello-world.md

As discussed in the following issues, this PR updates the documentation and instructs users to place `llama2-chat` and `codellama-instruct` models at `.spin/ai-models/llama/` instead of `.spin/ai-models/`
- https://github.com/fermyon/spin/issues/2467
- https://github.com/fermyon/developer/issues/1260
closes #1260 

Update docs and tutorials to place `llama2-chat` and `codellama-instruct` in the correct directory

---

content/cloud/develop.md
content/cloud/variables.md
content/spin/v2/install.md
content/spin/v2/managing-plugins.md
content/spin/v2/python-components.md
content/spin/v2/quickstart.md
content/spin/v2/serverless-ai-hello-world.md
content/spin/v2/variables.md
content/wasm-languages/python.md

✅ content/cloud/develop.md
✅ content/cloud/variables.md
✅ content/spin/v2/install.md
✅ content/spin/v2/managing-plugins.md
✅ content/spin/v2/python-components.md
✅ content/spin/v2/quickstart.md
✅ content/spin/v2/serverless-ai-hello-world.md
✅ content/spin/v2/variables.md

Update all py2wasm to componentize-py

---

content/cloud/variables.md
content/spin/v2/variables.md

Fix variables in manifest

---

content/spin/v2/testing-apps.md
templates/spin_sidebar_v2.hbs

```
$ bart check content/spin/v2/testing-apps.md 
✅ content/spin/v2/testing-apps.md
```

Adding spin test documentation

---

content/spin/v2/dynamic-configuration.md
content/spin/v2/variables.md

This PR adds documentation for using Azure Key Vault as application variable provider.
This should **not be merged before** the corresponding sample has been merged (https://github.com/fermyon/spin/pull/2483)

Azure Key Vault application variable provider support in Spin 2.5

---

content/spin/v2/cli-reference.md
content/spin/v2/triggers.md

Adding Spin 2.5 documentation

---

content/spin/v2/contributing-docs.md

Fixes https://github.com/fermyon/developer/issues/922

Use npm ci instead of npm install

---

README.md

Just aligns the README file with [the actual contribution docs](https://github.com/fermyon/developer/pull/1283/files) that were update last week.

Use `npm ci`, instead of `npm install` in the README

---

content/spin/v2/contributing-spin.md

This PR adds info about the Spin weekly calls to the contributions page.

add info about meetings to the spin contribution docs

---

content/spin/v2/cli-reference.md
content/spin/v2/spin-in-pods-legacy.md

SpinKube moved some docs around

---

content/spin/v2/http-trigger.md

Because people get bitten by it!  Supersedes #1330 - to my mind this is a more discoverable place for a warning.

Warn about the bonus favicon request from browser clients

---

content/spin/v2/manifest-reference.md
content/spin/v2/redis-trigger.md

Document Redis per-trigger server address

---

content/spin/v1/http-outbound.md
content/spin/v1/javascript-components.md
content/spin/v1/rdbms-storage.md
content/spin/v1/redis-outbound.md
content/spin/v2/build.md
content/spin/v2/http-outbound.md
content/spin/v2/http-trigger.md
content/spin/v2/javascript-components.md
content/spin/v2/key-value-store-tutorial.md
content/spin/v2/kv-store-api-guide.md
content/spin/v2/language-support-overview.md
content/spin/v2/mqtt-outbound.md
content/spin/v2/rdbms-storage.md
content/spin/v2/redis-outbound.md
content/spin/v2/serverless-ai-api-guide.md
content/spin/v2/sqlite-api-guide.md
content/spin/v2/variables.md

This PR updates the documentation to be based on the upcoming release of the v2 of the JS SDK.
Todo:

update js content to v2 sdk

---

content/wasm-languages/c-lang.md

<details>
<summary>Details</summary>
</details>

Update the version of the WASI-SDK in the C language guide

---

content/spin/v2/variables.md

Our variables example showed a bad example of checking passwords -- it does not at minimum do a constant time comparison. While it is an example, we cannot assume that folks will not use it. Instead, this updates the example to be a more realistic one that calls an API with a token. 
This also updates the examples to use the latest SDKs -- Python was out of date -- and talks about templating within the manifest.
I've run all examples locally -- here is a repo with the examples for if we need to test them for future sdk changes: https://github.com/kate-goldenring/spin-variables-examples

Update variables documentation with latest APIs and better example

---

content/spin/v2/http-outbound.md

Fix wildcard service chaining host string

---

content/spin/v2/cli-reference.md

Updated spin v2.7 cli reference docs as [per toolkit output](https://github.com/fermyon/developer/tree/main/toolkit) 
The changes between two different Spin versions(v2.6 and v2.7) script output. A quick necessary information for a new Spin CLI Reference PR.
```
< Output: spin 2.6.0 (a4ddd39 2024-06-20)
---
> Output: spin 2.7.0 (a111517 2024-07-30)
47a48,50
>         --allow-overwrite              If the output directory already contains files, generate the
>                                        new files into it without confirming, overwriting any
>                                        existing files with the same names
890a894,896
>         --allow-overwrite              If the output directory already contains files, generate the
>                                        new files …
```

Update docs for Spin v2.7 version bump

---

content/api/hub/plugin_spin_otel.md

Updating keywords to be a string in  plugin_spin_otel.md

---

content/spin/v2/install.md

- Updates the cargo install steps to remove the outdated/hard-coded version tag
- This is one approach to avoid needing to updating a hard-coded string... but then again there are others as well; so we could just decide to keep it around and add steps in the release process doc to update.
- Updates some older version strings

docs(spin/v2): update cargo install steps and version strings

---

content/api/hub/contributing.md
content/spin/v1/ai-sentiment-analysis-api-tutorial.md
content/spin/v1/serverless-ai-hello-world.md
content/spin/v2/ai-sentiment-analysis-api-tutorial.md
content/spin/v2/serverless-ai-hello-world.md
content/wasm-languages/python.md
spin-up-hub/index.html
spin-up-hub/src/store.js
spin-up-hub/src/view/Contributing.vue
templates/content_navbar.hbs
templates/home.hbs

Small terminology change for the name of the `/hub` section, to align with CLI work.
```
Spin Up Hub -> Spin Hub
```

rename spin up hub to spin hub

---

content/wasm-languages/webassembly-language-support.md

Update language matrix to be aligned with @kevmoo's https://github.com/fermyon/developer/commit/6cb4c1e4481c423dca3bc7d3c1fc7f4b952d2949
- Dart (and Flutter) have core and browser support: https://dart.dev/web/wasm
- WASI support is tracked in https://github.com/dart-lang/sdk/issues/56366

Update Dart webassembly-language-support.md

---

content/api/hub/plugin_spin_kinesis_trigger.md

- No new menu item
- Ran: `bart check content/api/hub/plugin_spin_kinesis_trigger.md`
- Output: `✅ content/api/hub/plugin_spin_kinesis_trigger.md`
- `All the errors were transient. The links are valid!`
- Blog has not yet been published, but I will add a link soon!

Add spin kinesis trigger plugin info

---

content/api/hub/template_angular.md

Updating Spin Hub

---

content/cloud/quickstart.md
content/spin/v1/deploying-to-fermyon.md
content/spin/v2/deploying-to-fermyon.md

Use GitHub repo links for Fermyon Platform
Ref https://github.com/fermyon/installer/pull/137

docs(*): use fermyon/installer links

---

content/spin/v2/variables.md
content/spin/v3/contributing-docs.md
content/spin/v3/http-trigger.md
content/spin/v3/managing-plugins.md
content/spin/v3/python-components.md
content/spin/v3/quickstart.md
content/spin/v3/registry-tutorial.md
content/spin/v3/running-apps.md
content/spin/v3/variables.md
content/wasm-languages/standards.md

Mostly related to v3 removing the CLI reference but also general background churn of outbound links.

Fix some broken links

---

content/spin/v3/http-trigger.md
content/spin/v3/manifest-reference-v1.md
content/spin/v3/manifest-reference.md
content/spin/v3/quickstart.md
content/spin/v3/template-authoring.md
content/spin/v3/writing-apps.md

Fixes #1371.
I think I got all of them but egad it's not the easiest string to search for.  In future can we name our settings "elephant" or "dodecahedron" kthxbai

Remove references to HTTP application base

---

content/wasm-languages/go-lang.md

This PR originally started with the goal of updating the example manifest to v2 and removing the `base` trigger config due to be removed in Spin 3 (ref https://github.com/fermyon/developer/issues/1376#issuecomment-2433510305).
I coudn't help but update a few tangential items along the way, but stopped short of revising the go/tinygo lay-of-the-land.
We can either collaborate in this PR to update the main text to reflect recent go/tinygo updates/support (pinging @adamreese @rajatjindal and others) or this can be a follow-up.

docs(wasm-languages): go updates

---

content/wasm-languages/rust.md

Mostly focused on updating the example app code/spin.toml, similar to https://github.com/fermyon/developer/pull/1403

docs(wasm-languages): rust updates

---

content/wasm-languages/ruby.md

Sample setup/code/manifest updates similar to https://github.com/fermyon/developer/pull/1403
Bonus: I did see the following error in the app logs when pinging the endpoint.  Cause for alarm?  Fixable?  (Response was still a 200 and contained the expected "Hello, Fermyon" body)
```
$ spin up
Logging component stdio to ".spin/logs/"
Serving http://127.0.0.1:3000
Available Routes:
ruby: http://127.0.0.1:3000
2024-10-30T22:37:06.498213Z ERROR spin_http::wagi: Invalid header name error=invalid HTTP header name header_name=ruby 3.4.0dev (2024-06-28T17
```

docs(wasm-languages): ruby updates

---

content/wasm-languages/grain.md

Mostly focused on updating the example app code/spin.toml, similar to https://github.com/fermyon/developer/pull/1403
Also ref https://github.com/fermyon/developer/issues/1376#issue-2497954855
I didn't touch the overview text or links at the bottom (pointing to older examples in the deislabs repos) -- do we want to update these at this time?  Any other mods/additions?

docs(wasm-languages): grain updates

---

content/wasm-languages/swift.md

Ref https://github.com/fermyon/developer/issues/1376

docs(wasm-languages): swift updates

---

content/spin/v3/managing-plugins.md
content/spin/v3/plugin-authoring.md
content/spin/v3/quickstart.md

Remove js2wasm from v3 docs

---

content/spin/v3/http-outbound.md
content/spin/v3/running-apps.md

You can't use selective deployment with wildcard service chaining

---

spin-up-hub/src/components/ContentListing.vue

Fixes: #1374
Link: https://fermyon-developer-jvfddbpo.fermyon.app/hub

Added a message to search when no items match

---

content/spin/v3/observing-apps.md

 Update docs for observing Spin Apps (adding .NET Aspire Stack)

---

content/spin/v2/writing-apps.md
content/spin/v3/writing-apps.md

Fix statement that all triggers must be same type

---

templates/spin_main.hbs

Adds the notice about there being a newer version of Spin for all versions before `v3`.

add redirect banner to spin v2 content

---

content/wasm-languages/javascript.md
content/wasm-languages/python.md

The site appears defunct, giving invalid SSL certificate errors and triggering ad blockers willy nilly.  We should avoid linking to it unless it reactivates.

Remove `wasm.builders` links

---

content/bartholomew/quickstart.md

Part of fix for https://github.com/fermyon/feedback/issues/57

Add Rust installation links and guidance to bart quickstart

---

content/spin/v3/key-value-store-tutorial.md

Fixed documentation: Go example was missing because it was inside Python's one

Fixed documentation Go example

---

content/spin/v3/contributing-docs.md

Signing contributions is required not recommended

---

downloads/install.sh

Addresses https://github.com/fermyon/spin/issues/2946.
Until https://github.com/fermyon/spin/pull/2947 is part of the release, the install script will fail if a pre-0.10 Cloud plugin is already installed.  This inserts a workaround so that the install can completely successfully even before that fix lands.

Work around Cloud plugin install woe

---

spin-up-hub/src/components/ContentListing.vue

Spin Up Hub language filters does not work, because of a spelling mistake.

Fix Spin Up Hub language filter

---

.github/workflows/deploy.yml

Explicitly sets the tailscale version to the [most recent](https://github.com/tailscale/tailscale/releases/tag/v1.78.1) as of writing.
Otherwise, the most recent v2 release of the GH action ([alas, not very recent](https://github.com/tailscale/github-action/releases/tag/v2)) defaults to a [very old version of tailscale](https://github.com/tailscale/github-action/issues/147).

fix(.github): pin tailscale to 1.78.1 for deploy

---

content/wasm-languages/javascript.md

There is additional work to be done on the contextual material, which is very out of date, but that needs input from @karthik2804 and/or @tschneidereit, so I am deferring that to a separate PR.

Remove js2wasm from language guide

---

content/spin/v3/plugin-authoring.md

Fixes #1386.  @michelleN I wasn't quite sure how to fit it into the explanation of the packaging flow and I think this might be too far into the "where no-one can find it" zone.  Although in practice I think most plugin devs will find out about it by copying other plugins rather than by reading the docs so 🤷.  What do you reckon?

Mention pluginify in plugin authoring docs

---

content/spin/v3/dynamic-configuration.md

+ @ogghead (can't add you as a reviewer but would appreciate any comments you have - thanks!)

AWS key-value store configuration

---

content/spin/v3/managing-templates.md

Install templates from tarball

---

content/spin/v2/spin-in-pods-legacy.md

add explicit opt in for spin-on-pods

---

.build/check-broken-links.sh

Adding link to stop builds from failing due to transient errors.

add link to exclude list

---

content/spin/v3/dynamic-configuration.md

Fixes #1461.
Also took the opportunity to rationalise some punctuation and phrasing across the KV config types.  Yes, it's all glamour round here.

KV config should not encourage readers to think SQLite

---

content/spin/v3/http-trigger.md

Document reserved health check and status routes

---

content/spin/v3/contributing-spin.md

The CNCF blog post links to this page. Added a link to join the CNCF Slack channel here so folks would see it first.

add link to slack channel in contributing-spin.md

---

content/spin/v3/quickstart.md
content/spin/v3/troubleshooting-application-dev.md

Remove stuff about Spin debug logs from quickstart

---

content/spin/v3/quickstart.md

Fixes #1458 
I'm not ecstatic about the flow here - I kinda want the quick start to focus on giving users a clear and unambuguous route to success, rather than on suggesting other ways to do things.  On the other hand, we bought ourselves a butt-ton of complexity budget by getting rid of the stuff about `RUST_LOG` so may as well spend it on something useful.

Mention `spin watch` in quickstart

---

.build/check-broken-links.sh

I don't know why it fails.  curl from local machine shows a 200.  Onto the list of shame it goes.

Exclude coreutils page from link checking

---

content/spin/v3/quickstart.md

We had feedback that the quickstart was useless if another program was using port 3000 (we gave the user the impression that port 3000 was hardwired rather than a default).  I'm wary of trying to cover every option in the quickstart (I'd like it to remain focused on the "quick" and "start", and we're already jimmying in `spin watch` in this section), but let's see how this feels...

Show how to use a different port in the quickstart

---

content/spin/v3/variables.md

add troubleshooting section to variables doc

---

content/spin/v2/ai-sentiment-analysis-api-tutorial.md
content/spin/v2/http-outbound.md
content/spin/v2/install.md
content/spin/v2/javascript-components.md
content/spin/v2/key-value-store-tutorial.md
content/spin/v2/mqtt-outbound.md
content/spin/v2/quickstart.md
content/spin/v2/rdbms-storage.md
content/spin/v2/redis-outbound.md
content/spin/v2/serverless-ai-hello-world.md

Points at sdk-v2 branch for Links to github.com/fermyon/spin-js-sdk as we are preparing for a 3.0.0 release.

update spin v2 docs to point at sdk-v2 branch for JS

---

content/api/hub/pattern_long_running_jobs_over_http.md
content/api/hub/plugin_spin_otel.md
content/api/hub/sample_11ty.md
content/api/hub/sample_bookmarker.md
content/api/hub/sample_checklist.md
content/api/hub/sample_hugo.md
content/api/hub/sample_jinja2.md
content/api/hub/sample_kv_in_python.md
content/api/hub/sample_load_testing_spin_apps_with_k6.md
content/api/hub/sample_spin_wordle.md
content/api/hub/sample_todo.md
content/api/hub/template_angular.md
content/api/hub/template_jekyll.md
content/api/hub/template_nuxt.md
content/api/hub/template_sqlite_explorer.md
content/api/hub/template_zola_ssg.md

Clean hub tags

---

content/spin/v3/ai-sentiment-analysis-api-tutorial.md
content/spin/v3/build.md
content/spin/v3/javascript-components.md
content/spin/v3/key-value-store-tutorial.md
content/spin/v3/kv-store-api-guide.md
content/spin/v3/quickstart.md
content/spin/v3/rdbms-storage.md
content/spin/v3/serverless-ai-api-guide.md
content/spin/v3/serverless-ai-hello-world.md
content/spin/v3/sqlite-api-guide.md
content/spin/v3/variables.md

Updates examples to look like the JS SDK v3
ref: https://github.com/fermyon/spin-js-sdk/pull/319

update spin 3 docs to represent js sdk v3 structure

---

downloads/install.sh

Repos have moved so the script is failing. This fixes it to point to new location of releases.

Update install script to use spinframework/spin

---

downloads/install.sh

Updates the install script to:
1. detect if the OS is using musl and should use the bin with statically linked deps
2. the $OSTYPE is just "linux" to support OpenSUSE OS (issue described in discord [here](https://discord.com/channels/926888690310053918/1220198778288603247/1220206645544615976)
3. Removes unnecessary wrapping of spin directory in array which makes the syntax unsupported by `sh`

fix(install): update install script to support more OS types

---

content/spin/v3/http-outbound.md

Scheme doesn't matter for local service chaining

---

content/spin/v3/ai-sentiment-analysis-api-tutorial.md
content/spin/v3/build.md
content/spin/v3/go-components.md
content/spin/v3/http-trigger.md
content/spin/v3/key-value-store-tutorial.md
content/spin/v3/quickstart.md
content/spin/v3/rdbms-storage.md
content/spin/v3/redis-trigger.md
content/spin/v3/sqlite-api-guide.md
content/spin/v3/variables.md

This reflects a template update.
Do not merge until the template becomes current (probably v3.2).

Update TinyGo docs to reflect statics fix

---

templates/functions_sidebar.hbs

Temporarily removing incomplete tutorial until it is finished (see https://github.com/fermyon/a3000-docs/issues/228)

Removing cron tutorial from functions_sidebar.hbs

---

content/wasm-functions/deploy.md
content/wasm-functions/quickstart.md

Install aka plugin from registry

---

deploy/fermyon-developer.nomad

Bumps the spin version used to run the website to the latest 3.2.0.
[Recently ran into issues](https://github.com/fermyon/developer/pull/1523) with the older v2 version of Spin attempting to run a component built with a v3 version, as might be expected.

chore(deploy): bump spin to 3.2.0

---

content/wasm-languages/webassembly-language-support.md

Modify the language rec here:
> We are often asked which languages are best supported for production-grade WebAssembly. We suggest C/C++, Rust, and AssemblyScript.
_Changed to Rust, JavaScript/TypeScript, Python and Go._

[wasm-languages] update the recommended languages

---

content/wasm-functions/app-linking.md

Move workspace explanation out of aside

---

content/wasm-functions/changelog/changelog-aka-plugin-v04.md

[Fix aka plugin v04 changelog link for app linking](https://github.com/fermyon/developer/commit/8fa4d9bc3599094a019fe46c52b7bd020f85382b)

Fix aka plugin v04 changelog link for app linking

---

content/wasm-functions/http-trigger-reference.md
templates/functions_sidebar.hbs

- Adds info around request headers that guest applications on FwF can expect, but starts a new, more generic doc to hold this information; 'HTTP Trigger Reference' seemed appropriate but feedback welcome.

docs(functions): add http trigger doc, request header info

---

content/wasm-functions/github-actions.md

- For some reason, the relative `/deploy` link was considered broken by the link checker.  Perhaps because there are multiple `deploy.md` files?  In any case, updating to point to the version under `wasm-functions` appears to fix it...

fix(github-actions.md): fix 'broken link'

---

content/index.md
templates/content_navbar.hbs

Closes https://github.com/fermyon/developer/issues/1493
Wanted to indicate that the Spin Hub now links to an [external site](https://spinframework.dev/hub).  Thus,
- Added the arrow img to appropriate links (~~is it overkill or distracting having it on the link in the text under 'Start Building'?~~ _edit: the external arrow didn't look quite right there so I removed it_) 
- Have link open new tab
I didn't update the cards to add the arrow, but we could.  The `card_element` shortcode is also used in the wasm-functions section which link to external fwf-examples, so it would apply there, too.

feat(*): indicate Spin Hub links to an external site

---

content/wasm-functions/changelog/changelog-aka-plugin-v04.md
content/wasm-functions/changelog/changelog-aka-plugin-v041.md
content/wasm-functions/changelog/changelog-aka-plugin-v042.md

Move the breaks so that more (basically all) of each changelog post is shown.  Otherwise, the view looks fairly undifferentiated.
Currently the page looks like:
With this change, it would look like:

docs(wasm-functions): show more of each changelog post
